SELECT 
  '- Enter Text to Filter Step Definition -' as label, 
  '- Enter Text to Filter Step Definition -' as NAME, 
  null as ID, 
  '- Enter Text to Filter Step Definition -' as value 
FROM 
  STEP_DEFINITION_TEMPLATE_VERBIAGE 
UNION 
SELECT 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label, 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME, 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID, 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value 
FROM 
  STEP_DEFINITION_TEMPLATE_VERBIAGE 
where 
  IS_POSSIBLE_FIRST_STEP = 'Yes' 
  AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' 
  AND (CONCAT(',',:STEP_FILTER, ',') like CONCAT('%,', STEP_FILTER, ',%') 
    OR STEP_FILTER LIKE :STEP_DEFINITION_FILTER) 
  AND ((CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :FUNCTIONAL_AREA_UUID, ',%')) OR
		(CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(FUNCTIONAL_AREA_UUID, '') = '') OR
		(COALESCE(TENANT_UUID, '') = '' AND COALESCE(FUNCTIONAL_AREA_UUID, '') = ''))
UNION 
SELECT 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label, 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME, 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID, 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value 
FROM 
  STEP_DEFINITION_TEMPLATE_VERBIAGE 
where 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID =:STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID




  SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM STEP_DEFINITION_TEMPLATE_VERBIAGE WHERE STEP_FILTER=:UIFilterTypeForVerBage AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE='Yes' and APPLICABLE_UI_ELEMENT_TYPE in(${strSelectedUIElementType}) AND ((CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :APP_LOGGED_IN_FUNTIONAL_AREA_ID, ',%')) OR(CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(FUNCTIONAL_AREA_UUID, '') = '') OR (COALESCE(TENANT_UUID, '') = '' AND COALESCE(FUNCTIONAL_AREA_UUID, '') = ''))




SELECT SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM STEP_DEFINITION_TEMPLATE_VERBIAGE SDTV INNER JOIN STEP_DEFINITION_ATTRIBUTE SDA ON SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID = SDA.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID WHERE SDTV.STEP_FILTER=:UIFilterTypeForVerBage AND SDTV.IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE='Yes' AND SDA.STEP_DEFINITION_ATTRIBUTE_MASTER_UUID="adcf6e25-f890-476c-bdcf-e723c6d7894c" order by STEP_DEFINITION_ATTRIBUTE_ID asc



  AND ((CONCAT(',', SDTV.TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', SDTV.FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :APP_LOGGED_IN_FUNTIONAL_AREA_ID, ',%')) OR(CONCAT(',', SDTV.TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(SDTV.FUNCTIONAL_AREA_UUID, '') = '') OR (COALESCE(SDTV.TENANT_UUID, '') = '' AND COALESCE(SDTV.FUNCTIONAL_AREA_UUID, '') = ''))


  AND ((CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :APP_LOGGED_IN_FUNTIONAL_AREA_ID, ',%')) OR(CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(FUNCTIONAL_AREA_UUID, '') = '') OR (COALESCE(TENANT_UUID, '') = '' AND COALESCE(FUNCTIONAL_AREA_UUID, '') = ''))





  SELECT SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM STEP_DEFINITION_TEMPLATE_VERBIAGE SDTV INNER JOIN STEP_DEFINITION_ATTRIBUTE SDA ON SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID = SDA.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID WHERE SDTV.STEP_FILTER=:UIFilterTypeForVerBage AND SDTV.IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE='Yes' AND SDA.STEP_DEFINITION_ATTRIBUTE_MASTER_UUID="adcf6e25-f890-476c-bdcf-e723c6d7894c" AND ((CONCAT(',', SDTV.TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', SDTV.FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :APP_LOGGED_IN_FUNTIONAL_AREA_ID, ',%')) OR(CONCAT(',', SDTV.TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(SDTV.FUNCTIONAL_AREA_UUID, '') = '') OR (COALESCE(SDTV.TENANT_UUID, '') = '' AND COALESCE(SDTV.FUNCTIONAL_AREA_UUID, '') = '')) order by STEP_DEFINITION_ATTRIBUTE_ID asc




  SELECT * FROM STEP_DEFINITION_TEMPLATE_VERBIAGE WHERE STEP_FILTER in (${stepDefinitionFilter}) AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' and APPLICABLE_UI_ELEMENT_TYPE in (${uIElementType}) AND ((CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :APP_LOGGED_IN_FUNTIONAL_AREA_ID, ',%')) OR(CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(FUNCTIONAL_AREA_UUID, '') = '') OR (COALESCE(TENANT_UUID, '') = '' AND COALESCE(FUNCTIONAL_AREA_UUID, '') = ''))



  SELECT * FROM STEP_DEFINITION_TEMPLATE_VERBIAGE WHERE STEP_FILTER in(${stepDefinitionFilter}) AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' AND ((CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :APP_LOGGED_IN_FUNTIONAL_AREA_ID, ',%')) OR(CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(FUNCTIONAL_AREA_UUID, '') = '') OR (COALESCE(TENANT_UUID, '') = '' AND COALESCE(FUNCTIONAL_AREA_UUID, '') = ''))




  SELECT ${testSetQueryData[0]['Test Set ID']} as 'Test Set ID', ${testSetQueryData[0]['Test Set ID']} as 'Test Case ID', '' as 'Test Case Step ID', '' as 'Test Case Step Seq ID', ${testCaseStepType} as 'Test Case Step Type', '' as 'Test Case Step Name', STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as 'Step Definition Template', '' as v1, '' as v2, '' as v3, '' as v4, '' as v5, '' as 'Test Case Sep Group Name', '' as reserved2,${testSetQueryData[0]['Test Set ID']} as 'Page ID', 'Active' as Status,uuid() as 'Test Case Step UUID',STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM STEP_DEFINITION_TEMPLATE_VERBIAGE WHERE STEP_FILTER in(${stepDefinitionFilter}) AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE='Yes' and APPLICABLE_UI_ELEMENT_TYPE in(${uIElementType}) AND ((CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :APP_LOGGED_IN_FUNTIONAL_AREA_ID, ',%')) OR(CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(FUNCTIONAL_AREA_UUID, '') = '') OR (COALESCE(TENANT_UUID, '') = '' AND COALESCE(FUNCTIONAL_AREA_UUID, '') = ''))




  SELECT ${testSetQueryData[0]['Test Set ID']} as 'Test Set ID', ${testSetQueryData[0]['Test Set ID']} as 'Test Case ID', '' as 'Test Case Step ID', '' as 'Test Case Step Seq ID', ${testCaseStepType} as 'Test Case Step Type', '' as 'Test Case Step Name', STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as 'Step Definition Template', '' as v1, '' as v2, '' as v3, '' as v4, '' as v5, '' as 'Test Case Sep Group Name', '' as reserved2,${testSetQueryData[0]['Test Set ID']} as 'Page ID', 'Active' as Status,uuid() as 'Test Case Step UUID',STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM STEP_DEFINITION_TEMPLATE_VERBIAGE WHERE STEP_FILTER in(${stepDefinitionFilter}) AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE='Yes' AND ((CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :APP_LOGGED_IN_FUNTIONAL_AREA_ID, ',%')) OR(CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(FUNCTIONAL_AREA_UUID, '') = '') OR (COALESCE(TENANT_UUID, '') = '' AND COALESCE(FUNCTIONAL_AREA_UUID, '') = ''))



  SELECT * FROM STEP_DEFINITION_TEMPLATE_VERBIAGE WHERE STEP_FILTER=${dataForVerbage} AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE='Yes' AND ((CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :APP_LOGGED_IN_FUNTIONAL_AREA_ID, ',%')) OR(CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(FUNCTIONAL_AREA_UUID, '') = '') OR (COALESCE(TENANT_UUID, '') = '' AND COALESCE(FUNCTIONAL_AREA_UUID, '') = ''))



  SELECT * FROM STEP_DEFINITION_TEMPLATE_VERBIAGE SDTV INNER JOIN STEP_DEFINITION_ATTRIBUTE SDA ON SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID = SDA.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID WHERE SDTV.STEP_FILTER=${dataForVerbage} AND SDTV.IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE='Yes' AND SDA.STEP_DEFINITION_ATTRIBUTE_MASTER_UUID='adcf6e25-f890-476c-bdcf-e723c6d7894c' AND ((CONCAT(',', SDTV.TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', SDTV.FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :APP_LOGGED_IN_FUNTIONAL_AREA_ID, ',%')) OR(CONCAT(',', SDTV.TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(SDTV.FUNCTIONAL_AREA_UUID, '') = '') OR (COALESCE(SDTV.TENANT_UUID, '') = '' AND COALESCE(SDTV.FUNCTIONAL_AREA_UUID, '') = ''))





  SELECT * FROM STEP_DEFINITION_TEMPLATE_VERBIAGE WHERE STEP_FILTER in (${stepDefinitionFilter}) AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' and APPLICABLE_UI_ELEMENT_TYPE in (${uIElementType}) AND ((CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :APP_LOGGED_IN_FUNTIONAL_AREA_ID, ',%')) OR(CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(FUNCTIONAL_AREA_UUID, '') = '') OR (COALESCE(TENANT_UUID, '') = '' AND COALESCE(FUNCTIONAL_AREA_UUID, '') = '')) AND STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID NOT IN (${restrictedStepDefinitionsString})




  SELECT * FROM STEP_DEFINITION_TEMPLATE_VERBIAGE WHERE STEP_FILTER in(${stepDefinitionFilter}) AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' AND ((CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :APP_LOGGED_IN_FUNTIONAL_AREA_ID, ',%')) OR(CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(FUNCTIONAL_AREA_UUID, '') = '') OR (COALESCE(TENANT_UUID, '') = '' AND COALESCE(FUNCTIONAL_AREA_UUID, '') = '')) AND STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID NOT IN (${restrictedStepDefinitionsString})


SELECT 1 FROM VIEW_NAVIGATION_STEP vns JOIN PAGE_VIEW v ON v.VIEW_UUID = vns.VIEW_UUID WHERE v.PAGE_UUID = tcs.CURRENT_PAGE_CONTEXT

SELECT 1 FROM TEST_CASE_STEP vns JOIN TEST_SET pnts ON vns.TEST_SET_UUID = pnts.TEST_SET_UUID WHERE pnts.PAGE_UUID = tcfs.CURRENT_PAGE_CONTEXT AND pnts.TEST_SET_TYPE = 'Page Navigation'


SELECT 1 FROM VIEW_NAVIGATION_STEP vns JOIN PAGE_VIEW v ON v.VIEW_UUID = vns.VIEW_UUID WHERE v.PAGE_UUID = tcfs.CURRENT_PAGE_CONTEXT


SELECT ts.TEST_SET_ID AS 'Test Set ID', tc.TEST_CASE_ID AS 'Test Case ID', CONCAT( tcs.TEST_CASE_STEP_SEQ_ID, '-', vns.TEST_CASE_STEP_SEQ_ID ) AS 'Test Case Step ID', vns.TEST_CASE_STEP_SEQ_ID AS 'Test Case Step Seq ID', vns.TEST_CASE_STEP_TYPE AS 'Test Case Step Type', '' AS 'Test Case Step Name', '' AS 'Step Definition Template', '' AS v1, '' AS v2, '' AS v3, '' AS v4, '' AS v5, CONCAT( ( SELECT PAGE_NAME FROM PAGE pn WHERE pn.PAGE_UUID = tcs.CURRENT_PAGE_CONTEXT ), ' Page - ', ' Navigation Step') AS 'Test Case Step Group Name', '' AS reserved2,CASE WHEN vns.NEXT_PAGE_CONTEXT IS NOT NULL THEN ( SELECT PAGE_ID FROM PAGE pn WHERE pn.PAGE_UUID = vns.NEXT_PAGE_CONTEXT ) ELSE ( SELECT PAGE_ID FROM PAGE pn WHERE pn.PAGE_UUID = vns.CURRENT_PAGE_CONTEXT ) END AS 'Page ID','Active' AS Status, vns.TEST_CASE_STEP_UUID AS 'Test Case Step UUID', '' as actions, '' AS v6, tcs.API_UUID, tcs.PLAYWRITE_STEP_CODE, tc.TEST_CASE_EXECUTON_TYPE, 'TEST_CASE_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_STEP_UUID' as PRIMARY_COLUMN_NAME, vns.TEST_CASE_STEP_UUID as PRIMARY_COLUMN_VALUE, vns.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM TEST_CASE_STEP vns, PAGE_VIEW pv, TEST_CASE_STEP tcs, TEST_CASE tc, TEST_SET ts WHERE ts.TEST_SET_UUID = tcs.TEST_SET_UUID AND tc.TEST_CASE_UUID = tcs.TEST_CASE_UUID AND tcs.CURRENT_PAGE_CONTEXT = pv.PAGE_UUID AND pv.VIEW_UUID = vns.VIEW_UUID AND tcs.TEST_SET_UUID=:TEST_SET_UUID AND tcs.IS_UI_ELEMENT_GROUP_STEP = 'No' AND tcs.IS_FUNCTION_STEP = 'No' AND tc.TEST_CASE_EXECUTON_TYPE=:AUTOMATION_TYPE AND tcs.IS_PURE_NAVIGATION_STEP = 'Yes' AND EXISTS( SELECT 1 FROM TEST_CASE_STEP vns JOIN TEST_SET pnts ON vns.TEST_SET_UUID = pnts.TEST_SET_UUID WHERE pnts.PAGE_UUID = tcs.CURRENT_PAGE_CONTEXT AND pnts.TEST_SET_TYPE = 'Page Navigation' ) ORDER BY vns.TEST_CASE_STEP_ID, vns.TEST_CASE_STEP_SEQ_ID ASC;




SELECT ts.TEST_SET_ID AS 'Test Set ID', tc.TEST_CASE_ID AS 'Test Case ID', CONCAT( tcs.TEST_CASE_STEP_SEQ_ID, '-', tcfs.TEST_CASE_FUNCTION_STEP_SEQ_ID, '-', vns.TEST_CASE_STEP_SEQ_ID ) AS 'Test Case Step ID', vns.TEST_CASE_STEP_SEQ_ID AS 'Test Case Step Seq ID', vns.TEST_CASE_STEP_TYPE AS 'Test Case Step Type', STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME AS 'Test Case Step Name', '' AS 'Step Definition Template', '' AS v1, '' AS v2, '' AS v3, '' AS v4, '' AS v5, CONCAT( ( SELECT FUNCTION_NAME FROM featuremanagement_app.FUNCTION f WHERE f.FUNCTION_UUID = tcfs.FUNCTION_UUID ), ' Function - ', ( SELECT PAGE_NAME FROM PAGE pn WHERE pn.PAGE_UUID = tcfs.CURRENT_PAGE_CONTEXT ), ' Page - ', 'Navigation Step') AS 'Test Case Step Group Name', '' AS reserved2,CASE WHEN vns.NEXT_PAGE_CONTEXT IS NOT NULL THEN ( SELECT PAGE_ID FROM PAGE pn WHERE pn.PAGE_UUID = vns.NEXT_PAGE_CONTEXT ) ELSE ( SELECT PAGE_ID FROM PAGE pn WHERE pn.PAGE_UUID = vns.CURRENT_PAGE_CONTEXT ) END AS 'Page ID','Active' AS Status, vns.TEST_CASE_STEP_UUID AS 'Test Case Step UUID', '' as actions, '' AS v6, tcs.API_UUID, tcs.PLAYWRITE_STEP_CODE, tc.TEST_CASE_EXECUTON_TYPE , 'TEST_CASE_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_STEP_UUID' as PRIMARY_COLUMN_NAME, vns.TEST_CASE_STEP_UUID as PRIMARY_COLUMN_VALUE, vns.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM TEST_CASE_STEP vns, PAGE_VIEW pv, TEST_CASE_FUNCTION_STEP tcfs, STEP_DEFINITION_TEMPLATE_VERBIAGE tcsd, TEST_CASE_STEP tcs, TEST_CASE tc, TEST_SET ts WHERE ts.TEST_SET_UUID = tcs.TEST_SET_UUID AND tc.TEST_CASE_UUID = tcs.TEST_CASE_UUID AND tcfs.TEST_CASE_STEP_UUID = tcs.TEST_CASE_STEP_UUID AND vns.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID = tcsd.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID AND tcs.TEST_SET_UUID=:TEST_SET_UUID AND tcfs.CURRENT_PAGE_CONTEXT = pv.PAGE_UUID AND pv.VIEW_UUID = (SELECT ASSOCIATED_VIEW_UUID FROM TEST_CASE WHERE TEST_CASE_UUID = vns.TEST_CASE_UUID) AND tcfs.IS_UI_ELEMENT_GROUP_STEP = 'No' AND tc.TEST_CASE_EXECUTON_TYPE=:AUTOMATION_TYPE AND tcfs.IS_PURE_NAVIGATION_STEP = 'Yes' AND EXISTS( SELECT 1 FROM TEST_CASE_STEP vns JOIN TEST_SET pnts ON vns.TEST_SET_UUID = pnts.TEST_SET_UUID WHERE pnts.PAGE_UUID = tcfs.CURRENT_PAGE_CONTEXT AND pnts.TEST_SET_TYPE = 'Page Navigation' ) ORDER BY vns.TEST_CASE_STEP_ID, vns.TEST_CASE_STEP_SEQ_ID ASC;





SELECT ts.TEST_SET_ID AS 'Test Set ID', tc.TEST_CASE_ID AS 'Test Case ID', CONCAT( tcs.TEST_CASE_STEP_SEQ_ID, '-', vns.TEST_CASE_STEP_SEQ_ID ) AS 'Test Case Step ID', vns.TEST_CASE_STEP_SEQ_ID AS 'Test Case Step Seq ID', vns.TEST_CASE_STEP_TYPE AS 'Test Case Step Type', '' AS 'Test Case Step Name', '' AS 'Step Definition Template', '' AS v1, '' AS v2, '' AS v3, '' AS v4, '' AS v5, CONCAT(( SELECT PAGE_NAME FROM PAGE pn WHERE pn.PAGE_UUID = tcs.CURRENT_PAGE_CONTEXT ), ' Page - ', ' Navigation Step' ) AS 'Test Case Step Group Name', '' AS reserved2,CASE WHEN vns.NEXT_PAGE_CONTEXT IS NOT NULL THEN ( SELECT PAGE_ID FROM PAGE pn WHERE pn.PAGE_UUID = vns.NEXT_PAGE_CONTEXT ) ELSE ( SELECT PAGE_ID FROM PAGE pn WHERE pn.PAGE_UUID = vns.CURRENT_PAGE_CONTEXT ) END AS 'Page ID','Active' AS Status, vns.TEST_CASE_STEP_UUID AS 'Test Case Step UUID', '' as actions, '' AS v6, tcs.API_UUID, tcs.PLAYWRITE_STEP_CODE, tc.TEST_CASE_EXECUTON_TYPE, 'TEST_CASE_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_STEP_UUID' as PRIMARY_COLUMN_NAME, vns.TEST_CASE_STEP_UUID as PRIMARY_COLUMN_VALUE, vns.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM TEST_CASE_STEP vns, PAGE_VIEW pv, TEST_CASE_STEP tcs, TEST_CASE tc, TEST_SET ts WHERE ts.TEST_SET_UUID = tcs.TEST_SET_UUID AND tc.TEST_CASE_UUID = tcs.TEST_CASE_UUID AND tcs.CURRENT_PAGE_CONTEXT = pv.PAGE_UUID AND pv.VIEW_UUID = (SELECT ASSOCIATED_VIEW_UUID FROM TEST_CASE WHERE TEST_CASE_UUID = vns.TEST_CASE_UUID) AND tc.TEST_CASE_UUID=:TEST_CASE_UUID AND pv.IS_DEFAULT_VIEW = 'Yes' AND tcs.IS_UI_ELEMENT_GROUP_STEP = 'No' AND tcs.IS_FUNCTION_STEP = 'No' AND tcs.IS_PURE_NAVIGATION_STEP = 'Yes' AND EXISTS( SELECT 1 FROM TEST_CASE_STEP vns JOIN TEST_SET pnts ON vns.TEST_SET_UUID = pnts.TEST_SET_UUID WHERE pnts.PAGE_UUID = tcs.CURRENT_PAGE_CONTEXT AND pnts.TEST_SET_TYPE = 'Page Navigation' ) ORDER BY vns.TEST_CASE_STEP_ID, vns.TEST_CASE_STEP_SEQ_ID ASC;






SELECT ts.TEST_SET_ID AS 'Test Set ID', tc.TEST_CASE_ID AS 'Test Case ID', CONCAT( tcs.TEST_CASE_STEP_SEQ_ID, '-', tcfs.TEST_CASE_FUNCTION_STEP_SEQ_ID, '-', vns.TEST_CASE_STEP_SEQ_ID ) AS 'Test Case Step ID', vns.TEST_CASE_STEP_SEQ_ID AS 'Test Case Step Seq ID', vns.TEST_CASE_STEP_TYPE AS 'Test Case Step Type', STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME AS 'Test Case Step Name', '' AS 'Step Definition Template', '' AS v1, '' AS v2, '' AS v3, '' AS v4, '' AS v5, CONCAT( ( SELECT FUNCTION_NAME FROM featuremanagement_app.FUNCTION f WHERE f.FUNCTION_UUID = tcfs.FUNCTION_UUID ), ' Function - ', ( SELECT PAGE_NAME FROM PAGE pn WHERE pn.PAGE_UUID = tcfs.CURRENT_PAGE_CONTEXT ), ' Page - ', 'Navigation Step' ) AS 'Test Case Step Group Name', '' AS reserved2,CASE WHEN vns.NEXT_PAGE_CONTEXT IS NOT NULL THEN ( SELECT PAGE_ID FROM PAGE pn WHERE pn.PAGE_UUID = vns.NEXT_PAGE_CONTEXT ) ELSE ( SELECT PAGE_ID FROM PAGE pn WHERE pn.PAGE_UUID = vns.CURRENT_PAGE_CONTEXT ) END AS 'Page ID','Active' AS Status, vns.TEST_CASE_STEP_UUID AS 'Test Case Step UUID', '' as actions, '' AS v6, tcs.API_UUID, tcs.PLAYWRITE_STEP_CODE, tc.TEST_CASE_EXECUTON_TYPE, 'TEST_CASE_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_STEP_UUID' as PRIMARY_COLUMN_NAME, vns.TEST_CASE_STEP_UUID as PRIMARY_COLUMN_VALUE, vns.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM TEST_CASE_STEP vns, PAGE_VIEW v, TEST_CASE_FUNCTION_STEP tcfs, STEP_DEFINITION_TEMPLATE_VERBIAGE tcsd, TEST_CASE_STEP tcs, TEST_CASE tc, TEST_SET ts WHERE ts.TEST_SET_UUID = tcs.TEST_SET_UUID AND tc.TEST_CASE_UUID = tcs.TEST_CASE_UUID AND tcfs.TEST_CASE_STEP_UUID = tcs.TEST_CASE_STEP_UUID AND vns.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID = tcsd.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID AND tc.TEST_CASE_UUID=:TEST_CASE_UUID AND tcfs.CURRENT_PAGE_CONTEXT = v.PAGE_UUID AND v.VIEW_UUID = (SELECT ASSOCIATED_VIEW_UUID FROM TEST_CASE WHERE TEST_CASE_UUID = vns.TEST_CASE_UUID ) AND v.IS_DEFAULT_VIEW = 'Yes' AND tcfs.IS_UI_ELEMENT_GROUP_STEP = 'No' AND tcfs.IS_PURE_NAVIGATION_STEP = 'Yes' AND EXISTS( SELECT 1 FROM VIEW_NAVIGATION_STEP vns JOIN PAGE_VIEW pv ON pv.VIEW_UUID = vns.VIEW_UUID WHERE pv.PAGE_UUID = tcfs.CURRENT_PAGE_CONTEXT ) ORDER BY vns.TEST_CASE_STEP_ID, vns.TEST_CASE_STEP_SEQ_ID ASC;



SELECT 
  '- Enter Text to Filter Step Definition -' as label, 
  '- Enter Text to Filter Step Definition -' as NAME, 
  null as ID, 
  '- Enter Text to Filter Step Definition -' as value 
FROM 
  STEP_DEFINITION_TEMPLATE_VERBIAGE 
UNION 
SELECT 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label, 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME, 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID, 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value 
FROM 
  STEP_DEFINITION_TEMPLATE_VERBIAGE 
where 
  IS_POSSIBLE_FIRST_STEP = 'Yes' 
  AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' 
  AND (CONCAT(',',:STEP_FILTER, ',') like CONCAT('%,', STEP_FILTER, ',%') 
    OR STEP_FILTER LIKE :STEP_DEFINITION_FILTER) 
  AND ((CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND CONCAT(',', FUNCTIONAL_AREA_UUID, ',') like CONCAT('%,', :FUNCTIONAL_AREA_UUID, ',%')) OR
		(CONCAT(',', TENANT_UUID, ',') like CONCAT('%,', :TENANT_UUID, ',%') AND COALESCE(FUNCTIONAL_AREA_UUID, '') = '') OR
		(COALESCE(TENANT_UUID, '') = '' AND COALESCE(FUNCTIONAL_AREA_UUID, '') = ''))
UNION 
SELECT 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label, 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME, 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID, 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value 
FROM 
  STEP_DEFINITION_TEMPLATE_VERBIAGE 
where 
  STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID =:STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID