INSERT INTO VIEW_UI_ELEMENT (VIEW_UI_ELEMENT_UUID,VIEW_UI_ELEMENT_ID,VIEW_UUID,PAGE_UUID,UI_ELEMENT_UUID,FUNCTIONAL_AREA_UUID,AE_INSERT_ID,AE_UPDATE_ID,AE_TRANSACTION_ID,AE_INSERT_TS,AE_UPDATE_TS) VALUES (:VIEW_UI_ELEMENT_UUID,:VIEW_UI_ELEMENT_ID,:VIEW_UUID,:PAGE_UUID,:UI_ELEMENT_UUID,:FUNCTIONAL_AREA_UUID,:APP_LOGGED_IN_USER_ID,:AE_UPDATE_ID,:AE_TRANSACTION_ID,:AE_INSERT_TS,:AE_UPDATE_TS)



UPDATE VIEW_UI_ELEMENT SET VIEW_UI_ELEMENT_UUID=:VIEW_UI_ELEMENT_UUID,VIEW_UI_ELEMENT_ID=:VIEW_UI_ELEMENT_ID,VIEW_UUID=:VIEW_UUID,PAGE_UUID=:PAGE_UUID,UI_ELEMENT_UUID=:UI_ELEMENT_UUID,FUNCTIONAL_AREA_UUID=:FUNCTIONAL_AREA_UUID,AE_INSERT_ID=:AE_INSERT_ID,AE_UPDATE_ID=:APP_LOGGED_IN_USER_ID,AE_TRANSACTION_ID=:AE_TRANSACTION_ID,AE_INSERT_TS=:AE_INSERT_TS,AE_UPDATE_TS=:AE_UPDATE_TS WHERE VIEW_UI_ELEMENT_UUID=:VIEW_UI_ELEMENT_UUID



SELECT VIEW_UI_ELEMENT_UUID,VIEW_UI_ELEMENT_ID,VIEW_UUID,PAGE_UUID,UI_ELEMENT_UUID,FUNCTIONAL_AREA_UUID,AE_INSERT_ID,AE_UPDATE_ID,AE_TRANSACTION_ID,AE_INSERT_TS,AE_UPDATE_TS FROM VIEW_UI_ELEMENT WHERE VIEW_UI_ELEMENT_UUID=:VIEW_UI_ELEMENT_UUID






SELECT UI_ELEMENT_TYPE_NAME as label,UI_ELEMENT_TYPE_NAME as NAME,UI_ELEMENT_TYPE_UUID as ID,UI_ELEMENT_TYPE_UUID as value FROM UI_ELEMENT ue,UI_ELEMENT_TYPE_MASTER uem where ue.UI_ELEMENT_TYPE=uem.UI_ELEMENT_TYPE_UUID AND ue.UI_ELEMENT_UUID=:USER_ACTION_NAME