SELECT 
    null as id, 
    '- Select -' as label,
    '- Select -' as value
FROM 
    STEP_DEFINITION_TEMPLATE_VERBIAGE SDTVV
UNION
SELECT 
    SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID AS id, 
    SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME AS label, 
    SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME AS value 
FROM 
    STEP_DEFINITION_TEMPLATE_VERBIAGE SDTV
JOIN 
    UI_ELEMENT_TYPE_MASTER UETM ON SDTV.APPLICABLE_UI_ELEMENT_TYPE = UETM.UI_ELEMENT_TYPE_NAME
JOIN 
    UI_ELEMENT UE ON UETM.UI_ELEMENT_TYPE_UUID = UE.UI_ELEMENT_TYPE
WHERE 
	:STEP_TYPE = 'User Input' 
    AND SDTV.STEP_FILTER = 'Input Step'
    AND SDTV.IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes'
    AND UE.UI_ELEMENT_UUID = :UI_ELEMENTS
UNION
SELECT 
	SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as id, 
	SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label , 
    SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as value 
FROM 
	STEP_DEFINITION_TEMPLATE_VERBIAGE SDTV 
INNER JOIN 
	STEP_DEFINITION_ATTRIBUTE SDA ON SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID = SDA.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID 
WHERE 
	:STEP_TYPE = 'Expected Result' 
	AND SDTV.STEP_FILTER='Expected Result Step'
	AND SDTV.IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE='Yes' 
	AND SDA.STEP_DEFINITION_ATTRIBUTE_MASTER_UUID="adcf6e25-f890-476c-bdcf-e723c6d7894c"