-- Test Case Step (Step Definition Name Initial)
SELECT  '- Enter Text to Filter Step Definition -' as label,'- Enter Text to Filter Step Definition -' as NAME,null as ID,'- Enter Text to Filter Step Definition -' as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE UNION SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label,STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE
where IS_POSSIBLE_FIRST_STEP='Yes' AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' AND (CONCAT(',',:STEP_FILTER,',') like CONCAT('%,',STEP_FILTER,',%') OR STEP_FILTER LIKE :STEP_DEFINITION_FILTER) UNION
SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label,STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE where STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID=:STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID


-- Test Case Step (Step Definition Name)
SELECT  '- Enter Text to Filter Step Definition -' as label,'- Enter Text to Filter Step Definition -' as NAME,null as ID,'- Enter Text to Filter Step Definition -' as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE UNION SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label,STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE where IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' AND (CONCAT(',',:STEP_FILTER,',') like CONCAT('%,',STEP_FILTER,',%') OR STEP_FILTER LIKE :STEP_DEFINITION_FILTER) UNION SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label,STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE where STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID=:STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID



--  Function Step (Step Definition Name Initial)
SELECT  '- Enter Text to Filter Step Definition -' as label,'- Enter Text to Filter Step Definition -' as NAME,null as ID,'- Enter Text to Filter Step Definition -' as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE UNION SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label,STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE
where (IS_API_CONTEXT_SETTER ='Yes' or IS_PAGE_CONTEXT_SETTER='Yes') AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' AND IS_POSSIBLE_FIRST_STEP='Yes' AND (CONCAT(',',:STEP_FILTER,',') like CONCAT('%,',STEP_FILTER,',%') OR STEP_FILTER LIKE :STEP_DEFINITION_FILTER) UNION SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label,STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE where STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID=:STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID



--  Function Step (Step Definition Name)
SELECT  '- Enter Text to Filter Step Definition -' as label,'- Enter Text to Filter Step Definition -' as NAME,null as ID,'- Enter Text to Filter Step Definition -' as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE UNION SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label,STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE where STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID not in('60253de5-90a0-4ccf-b40e-b07591813a23','367a979e-1457-417d-bb81-66108edcf755') AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' AND (CONCAT(',',:STEP_FILTER,',') like CONCAT('%,',STEP_FILTER,',%') OR STEP_FILTER LIKE :STEP_DEFINITION_FILTER) UNION SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label,STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE where STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID=:STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID







--  UI Element Group Step
SELECT 
    null as id, 
    '- Select -' as label,
    '- Select -' as value
FROM 
    STEP_DEFINITION_TEMPLATE_VERBIAGE SDTVV
UNION
SELECT 
    SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID AS id, 
    SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME AS label, 
    SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME AS value 
FROM 
    STEP_DEFINITION_TEMPLATE_VERBIAGE SDTV
JOIN 
    UI_ELEMENT_TYPE_MASTER UETM ON SDTV.APPLICABLE_UI_ELEMENT_TYPE = UETM.UI_ELEMENT_TYPE_NAME
JOIN 
    UI_ELEMENT UE ON UETM.UI_ELEMENT_TYPE_UUID = UE.UI_ELEMENT_TYPE
WHERE 
	:STEP_TYPE = 'User Input' 
    AND SDTV.STEP_FILTER = 'Input Step'
    AND SDTV.IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes'
    AND UE.UI_ELEMENT_UUID = :UI_ELEMENTS
UNION
SELECT 
	SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as id, 
	SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label , 
    SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as value 
FROM 
	STEP_DEFINITION_TEMPLATE_VERBIAGE SDTV 
INNER JOIN 
	STEP_DEFINITION_ATTRIBUTE SDA ON SDTV.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID = SDA.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID 
WHERE 
	:STEP_TYPE = 'Expected Result' 
	AND SDTV.STEP_FILTER='Expected Result Step'
	AND SDTV.IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE='Yes' 
    AND SDA.STEP_DEFINITION_ATTRIBUTE_MASTER_UUID="adcf6e25-f890-476c-bdcf-e723c6d7894c"




-- Page Navigation Step (Initial)

SELECT  '- Enter Text to Filter Step Definition -' as label,'- Enter Text to Filter Step Definition -' as NAME,null as ID,'- Enter Text to Filter Step Definition -' as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE UNION SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label,STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE
where IS_POSSIBLE_FIRST_STEP='Yes' AND IS_PAGE_CONTEXT_SETTER='Yes' AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' AND (CONCAT(',',:STEP_FILTER,',') like CONCAT('%,',STEP_FILTER,',%') OR STEP_FILTER LIKE :STEP_DEFINITION_FILTER) UNION SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label,STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE where STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID=:STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID



--  Page navigation Step
SELECT  '- Enter Text to Filter Step Definition -' as label,'- Enter Text to Filter Step Definition -' as NAME,null as ID,'- Enter Text to Filter Step Definition -' as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE UNION SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label,STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE where STEP_FILTER in('Navigation Step','Input and Action Step','Input Step','Scope Step','Action Step','Custom Step') AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' AND (CONCAT(',',:STEP_FILTER,',') like CONCAT('%,',STEP_FILTER,',%') OR STEP_FILTER LIKE :STEP_DEFINITION_FILTER) UNION SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label,STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE where STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID=:STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID



-- View UI Elemenent applicable step
SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label, STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE WHERE STEP_FILTER in(:STEP_FILTER) AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' and APPLICABLE_UI_ELEMENT_TYPE=:UI_ELEMENT_TYPE_NAME AND STEP_FILTER in('Input Step', 'Input and Action Step') UNION SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label, STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE WHERE STEP_FILTER in(:STEP_FILTER) AND IS_ACTIVE_STEP_DEFINITION_TEMPLATE_VERBIAGE = 'Yes' AND STEP_FILTER in('Expected Result Step','Action Step') UNION SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as label, STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME as NAME, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as ID, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID as value FROM STEP_DEFINITION_TEMPLATE_VERBIAGE WHERE STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID=:STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID AND COALESCE(:VIEW_UI_ELEMENT_APPLICABLE_STEP_UUID, '0' ) IS NOT NULL