SELECT USER_PROFILE_ID,USERID as APP_LOGGED_IN_USER_ID,concat(COALESCE(detail.FIRST_NAME,""), ' ' , COALESCE(detail.LAST_NAME,"")) as APP_LOGGED_IN_USER_NAME, USERID,role.ROLEID as APP_LOGGED_IN_ROLE_ID, ROLENAME as APP_LOGGED_IN_ROLENAME,    FIRST_NAME,     MIDDLE_NAME,     LAST_NAME,     EMAIL_ADDRESS,     PHOTO,     MOBILE_NUMBER,     DATE_OF_BIRTH,     GENDER,     AE_GRAMPANCHAYAT_ID,     AE_CREATEDBY,     AE_UPDATEDBY,     AE_CREATIONDATE,     AE_UPDATIONDATE,     AE_DELETIONDATE,     AE_TRANSACTION_ID FROM USER_PROFILE detail left join USERMAPPING map on USERID=USER_PROFILE_ID and MAPPINGTYPE='USER_PROJECT_ROLE' and PROJECTID=0 left join ROLE role on map.ROLEID=role.ROLEID










SELECT 
  null as id, 
  '- Select -' as value, 
  '- Select -' as label, 
  '- Select -' as NAME 
FROM 
  UI_ELEMENT 
UNION 
SELECT 
  UI_ELEMENT_UUID as id, 
  UI_ELEMENT_UUID as value, 
  UI_ELEMENT_NAME as label, 
  UI_ELEMENT_NAME as NAME 
FROM 
  UI_ELEMENT 
where 
  PAGE_NEW_UUID =: CURRENT_PAGE_CONTEXT 
  AND FUNCTIONAL_AREA_UUID =: APP_LOGGED_IN_FUNTIONAL_AREA_ID 
  AND(
    (
      CONCAT(',', UI_ELEMENT_MODE, ',') LIKE CONCAT('%,',: primaryMode, ',%')
    ) 
    OR(
      CONCAT(',', UI_ELEMENT_MODE, ',') LIKE CONCAT('%,',: secondaryMode, ',%')
    )
  ) 
  AND(
    : GRAND_PARENT_GRID_NAME != "Page Navigation Test Set" 
    OR : ORIGINAL_PAGE_UUID !=: CURRENT_PAGE_CONTEXT
  ) 
  AND '1' !=: FIRST_COLUMN_HEADER_NAME 
  AND UI_ELEMENT_TYPE in (
    SELECT 
      UI_ELEMENT_TYPE_UUID 
    FROM 
      UI_ELEMENT_TYPE_MASTER 
    WHERE 
      UI_ELEMENT_TYPE_NAME not in ('Table', 'Column Header')
  ) 
UNION 
SELECT 
  ue.UI_ELEMENT_UUID as id, 
  ue.UI_ELEMENT_UUID as value, 
  ue.UI_ELEMENT_NAME as label, 
  ue.UI_ELEMENT_NAME as NAME 
FROM 
  VIEW_UI_ELEMENT vue 
  JOIN UI_ELEMENT ue ON vue.UI_ELEMENT_UUID = ue.UI_ELEMENT_UUID 
where 
  vue.PAGE_UUID =: CURRENT_PAGE_CONTEXT 
  AND vue.VIEW_UUID =: ASSOCIATED_VIEW_UUID 
  AND ue.FUNCTIONAL_AREA_UUID =: APP_LOGGED_IN_FUNTIONAL_AREA_ID 
  AND(
    (
      CONCAT(',', ue.UI_ELEMENT_MODE, ',') LIKE CONCAT('%,',: primaryMode, ',%')
    ) 
    OR(
      CONCAT(',', ue.UI_ELEMENT_MODE, ',') LIKE CONCAT('%,',: secondaryMode, ',%')
    )
  ) 
  AND(
    : GRAND_PARENT_GRID_NAME = "Page Navigation Test Set" 
    AND : ORIGINAL_PAGE_UUID =: CURRENT_PAGE_CONTEXT
  ) 
  AND '1' !=: FIRST_COLUMN_HEADER_NAME 
  AND UI_ELEMENT_TYPE in (
    SELECT 
      UI_ELEMENT_TYPE_UUID 
    FROM 
      UI_ELEMENT_TYPE_MASTER 
    WHERE 
      UI_ELEMENT_TYPE_NAME not in ('Table', 'Column Header')
  ) 
UNION 
SELECT 
  UI_ELEMENT_UUID as id, 
  UI_ELEMENT_UUID as value, 
  UI_ELEMENT_NAME as label, 
  UI_ELEMENT_NAME as NAME 
FROM 
  UI_ELEMENT 
where 
  PAGE_NEW_UUID =: CURRENT_PAGE_CONTEXT 
  AND FUNCTIONAL_AREA_UUID =: APP_LOGGED_IN_FUNTIONAL_AREA_ID 
  AND(
    : GRAND_PARENT_GRID_NAME != "Page Navigation Test Set" 
    OR : ORIGINAL_PAGE_UUID !=: CURRENT_PAGE_CONTEXT
  ) 
  AND '1' =: FIRST_COLUMN_HEADER_NAME 
  AND UI_ELEMENT_TYPE in (
    SELECT 
      UI_ELEMENT_TYPE_UUID 
    FROM 
      UI_ELEMENT_TYPE_MASTER 
    WHERE 
      UI_ELEMENT_TYPE_NAME not in ('Table', 'Column Header')
  ) 
UNION 
SELECT 
  ue.UI_ELEMENT_UUID as id, 
  ue.UI_ELEMENT_UUID as value, 
  ue.UI_ELEMENT_NAME as label, 
  ue.UI_ELEMENT_NAME as NAME 
FROM 
  VIEW_UI_ELEMENT vue 
  JOIN UI_ELEMENT ue ON vue.UI_ELEMENT_UUID = ue.UI_ELEMENT_UUID 
where 
  vue.PAGE_UUID =: CURRENT_PAGE_CONTEXT 
  AND vue.VIEW_UUID =: ASSOCIATED_VIEW_UUID 
  AND ue.FUNCTIONAL_AREA_UUID =: APP_LOGGED_IN_FUNTIONAL_AREA_ID 
  AND(
    : GRAND_PARENT_GRID_NAME = "Page Navigation Test Set" 
    AND : ORIGINAL_PAGE_UUID =: CURRENT_PAGE_CONTEXT
  ) 
  AND '1' =: FIRST_COLUMN_HEADER_NAME 
  AND UI_ELEMENT_TYPE in (
    SELECT 
      UI_ELEMENT_TYPE_UUID 
    FROM 
      UI_ELEMENT_TYPE_MASTER 
    WHERE 
      UI_ELEMENT_TYPE_NAME not in ('Table', 'Column Header')
  )
