SELECT 
    r.REQUIREMENT_UUID,
    concat(r.REQUIREMENT_ID,' - ',r.REQUIREMENT_TEXT) as REQUIREMENT_TEXT,
    r.REQUIREMENT_ASSOCIATION_UUID,
    r.REQUIREMENT_ASSOCIATION_TYPE,
    r.IS_SOLO_REQUIREMENT,
    rs.REQUIREMENT_SET_UUID,
    concat(rs.REQUIREMENT_SET_ID,' - ',rs.REQUIREMENT_SET_NAME) as REQUIREMENT_SET_NAME,
    concat(cos.CONDITION_SATISFACTION_ID,' - ',cos.CONDITION_SATISFACTION_NAME) as CONDITION_SATISFACTION_NAME,
    cos.CONDITION_SATISFACTION_UUID,
    vua.USER_ACTION_UUID,
    :PAGE_UUID AS PAGE_UUID,
    :PROCESS_UUID AS PROCESS_UUID,
    :VIEW_UUID AS VIEW_UUID
FROM
    VIEW_USER_ACTION vua
        JOIN
    REQUIREMENT_SET rs ON vua.USER_ACTION_UUID = rs.REQUIREMENT_SET_ASSOCIATION_UUID
        AND rs.REQUIREMENT_SET_ASSOCIATION_TYPE = 'USER_ACTION'
        LEFT JOIN
    REQUIREMENT r ON rs.REQUIREMENT_SET_UUID = r.REQUIREMENT_SET_UUID
        AND r.REQUIREMENT_ASSOCIATION_TYPE = 'USER_ACTION'
        LEFT JOIN
    CONDITION_SATISFACTION cos ON r.REQUIREMENT_UUID = cos.REQUIREMENT_UUID
        AND cos.CONDITION_SATISFACTION_ASSOCIATION_TYPE = 'USER_ACTION'
WHERE
    vua.USER_ACTION_UUID = :USER_ACTION_UUID
UNION ALL SELECT 
    r.REQUIREMENT_UUID,
    concat(r.REQUIREMENT_ID,' - ',r.REQUIREMENT_TEXT) as REQUIREMENT_TEXT,
    r.REQUIREMENT_ASSOCIATION_UUID,
    r.REQUIREMENT_ASSOCIATION_TYPE,
    r.IS_SOLO_REQUIREMENT,
    NULL AS REQUIREMENT_SET_UUID,
    NULL AS REQUIREMENT_SET_NAME,
    concat(cos.CONDITION_SATISFACTION_ID,' - ',cos.CONDITION_SATISFACTION_NAME) as CONDITION_SATISFACTION_NAME,
    cos.CONDITION_SATISFACTION_UUID,
    vua.USER_ACTION_UUID,
    :PAGE_UUID AS PAGE_UUID,
    :PROCESS_UUID AS PROCESS_UUID,
    :VIEW_UUID AS VIEW_UUID
FROM
    VIEW_USER_ACTION vua
        LEFT JOIN
    REQUIREMENT r ON r.REQUIREMENT_ASSOCIATION_UUID = vua.USER_ACTION_UUID
        AND r.REQUIREMENT_ASSOCIATION_TYPE = 'USER_ACTION'
        LEFT JOIN
    CONDITION_SATISFACTION cos ON r.REQUIREMENT_UUID = cos.REQUIREMENT_UUID
        AND cos.CONDITION_SATISFACTION_ASSOCIATION_TYPE = 'USER_ACTION'
WHERE
    vua.USER_ACTION_UUID = :USER_ACTION_UUID
        AND r.REQUIREMENT_UUID NOT IN (SELECT 
            COALESCE(r.REQUIREMENT_UUID, 1)
        FROM
            VIEW_USER_ACTION vua
                LEFT JOIN
            REQUIREMENT_SET rs ON vua.USER_ACTION_UUID = rs.REQUIREMENT_SET_ASSOCIATION_UUID
                AND rs.REQUIREMENT_SET_ASSOCIATION_TYPE = 'USER_ACTION'
                LEFT JOIN
            REQUIREMENT r ON rs.REQUIREMENT_SET_UUID = r.REQUIREMENT_SET_UUID
                AND r.REQUIREMENT_ASSOCIATION_TYPE = 'USER_ACTION'
        WHERE
            vua.USER_ACTION_UUID = :USER_ACTION_UUID)
