try {
  AppengProcessConfig = global.get('AppengProcessConfig');
  const serviceOrchestrator = AppengProcessConfig.serviceOrchestrator;
  let queryData = [];
  let queryData_pre_defined = [];
  let input = Object.assign(msg.payload.apiRequestBody, msg.payload.referenceData);
  console.log(input, '***>>');
  function getDataFromAttributeValue(attributeValueQueryData, stepDefArrributeId, attributeData) {
    let result = attributeValueQueryData.filter((item) => item['STEP_DEFINITION_ATTRIBUTE_UUID'] == stepDefArrributeId);
    if (result && result.length) {
      return result[0][attributeData];
    } else {
      return '';
    }
  }
  function getFunctionDataFromAttributeValue(attributeValueQueryData, stepDefArrributeId) {
    let result = attributeValueQueryData.filter((item) => item['STEP_DEFINITION_ATTRIBUTE_UUID'] == stepDefArrributeId);
    if (result && result.length) {
      return result[0]['FUNCTION_UUID'];
    } else {
      return '';
    }
  }
  if (input && input.TEST_CASE_GRID_DE == 'DATA_ELEMENT_CHILD_TEST_CASE_STEP') {
    const selectQuery = `select * from ( SELECT tcs.TEST_CASE_STEP_ID AS ID, CONCAT(tcs.TEST_CASE_STEP_ID, ' - ', tcs.TEST_CASE_STEP_NAME) AS ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, de.DATA_ELEMENT_UUID, CONCAT(tc.TEST_CASE_ID, ' - ', tc.TEST_CASE_NAME) AS TEST_CASE_UUID, CONCAT(ts.TEST_SET_ID, ' - ', ts.TEST_SET_NAME) AS TEST_SET_UUID, tcs.FUNCTIONAL_AREA_UUID, tc.TEST_CASE_ID, ts.TEST_SET_ID, '' AS PARENT_GROUP FROM TEST_CASE_STEP_ATTRIBUTE_VALUE tsav JOIN TEST_CASE_STEP tcs ON tsav.TEST_CASE_STEP_UUID = tcs.TEST_CASE_STEP_UUID JOIN TEST_CASE tc ON tcs.TEST_CASE_UUID = tc.TEST_CASE_UUID JOIN TEST_SET ts ON tcs.TEST_SET_UUID = ts.TEST_SET_UUID JOIN info_tenant.PRE_DEFINED_VALUES pd ON tsav.PRE_DEFINED_VALUES_UUID = pd.PRE_DEFINED_VALUES_UUID JOIN DATA_ELEMENT de ON pd.CODE_SET_UUID = de.CODE_SET_UUID union all SELECT tcsf.TEST_CASE_FUNCTION_STEP_ID AS ID, CONCAT(tcsf.TEST_CASE_FUNCTION_STEP_ID, ' - ', tcsf.TEST_CASE_FUNCTION_STEP_NAME) AS ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, de.DATA_ELEMENT_UUID, CONCAT(tc.TEST_CASE_ID, ' - ', tc.TEST_CASE_NAME) AS TEST_CASE_UUID, CONCAT(ts.TEST_SET_ID, ' - ', ts.TEST_SET_NAME) AS TEST_SET_UUID, tcsf.FUNCTIONAL_AREA_UUID, tc.TEST_CASE_ID, ts.TEST_SET_ID, CONCAT(f.FUNCTION_ID, ' - ', f.FUNCTION_NAME, ' - Function') AS PARENT_GROUP FROM TEST_CASE_FUNCTION_STEP_ATTRIBUTE_VALUE tsav JOIN TEST_CASE_FUNCTION_STEP tcsf ON tsav.TEST_CASE_FUNCTION_STEP_UUID = tcsf.TEST_CASE_FUNCTION_STEP_UUID JOIN TEST_CASE_STEP tcs ON tcsf.TEST_CASE_STEP_UUID = tcs.TEST_CASE_STEP_UUID JOIN TEST_CASE tc ON tcs.TEST_CASE_UUID = tc.TEST_CASE_UUID JOIN TEST_SET ts ON tcs.TEST_SET_UUID = ts.TEST_SET_UUID JOIN featuremanagement_app.FUNCTION f ON tcsf.FUNCTION_UUID = f.FUNCTION_UUID JOIN info_tenant.PRE_DEFINED_VALUES pd ON tsav.PRE_DEFINED_VALUES_UUID = pd.PRE_DEFINED_VALUES_UUID JOIN DATA_ELEMENT de ON pd.CODE_SET_UUID = de.CODE_SET_UUID union all SELECT tcsf.TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_ID AS ID, CONCAT(tcsf.TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_ID, ' - ', tcsf.TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_NAME) AS ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, de.DATA_ELEMENT_UUID, CONCAT(tc.TEST_CASE_ID, ' - ', tc.TEST_CASE_NAME) AS TEST_CASE_UUID, CONCAT(ts.TEST_SET_ID, ' - ', ts.TEST_SET_NAME) AS TEST_SET_UUID, tcsf.FUNCTIONAL_AREA_UUID, tc.TEST_CASE_ID, ts.TEST_SET_ID, CONCAT(ug.UI_ELEMENT_GROUP_ID, ' - ', ug.UI_ELEMENT_GROUP_NAME, ' - UI Element Group') AS PARENT_GROUP FROM TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE tsav JOIN TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP tcsf ON tsav.TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_UUID = tcsf.TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_UUID JOIN TEST_CASE_STEP tcs ON tcsf.TEST_CASE_STEP_UUID = tcs.TEST_CASE_STEP_UUID JOIN TEST_CASE tc ON tcs.TEST_CASE_UUID = tc.TEST_CASE_UUID JOIN TEST_SET ts ON tcs.TEST_SET_UUID = ts.TEST_SET_UUID JOIN UI_ELEMENT_GROUP ug ON tcsf.UI_ELEMENT_GROUP_UUID = ug.UI_ELEMENT_GROUP_UUID JOIN info_tenant.PRE_DEFINED_VALUES pd ON tsav.PRE_DEFINED_VALUES_UUID = pd.PRE_DEFINED_VALUES_UUID JOIN DATA_ELEMENT de ON pd.CODE_SET_UUID = de.CODE_SET_UUID union all SELECT tcsf.TEST_CASE_UI_ELEMENT_GROUP_STEP_ID AS ID, CONCAT(tcsf.TEST_CASE_UI_ELEMENT_GROUP_STEP_ID, ' - ', tcsf.TEST_CASE_UI_ELEMENT_GROUP_STEP_NAME) AS ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, de.DATA_ELEMENT_UUID, CONCAT(tc.TEST_CASE_ID, ' - ', tc.TEST_CASE_NAME) AS TEST_CASE_UUID, CONCAT(ts.TEST_SET_ID, ' - ', ts.TEST_SET_NAME) AS TEST_SET_UUID, tcsf.FUNCTIONAL_AREA_UUID, tc.TEST_CASE_ID, ts.TEST_SET_ID, CONCAT(ug.UI_ELEMENT_GROUP_ID, ' - ', ug.UI_ELEMENT_GROUP_NAME, ' - UI Element Group') AS PARENT_GROUP FROM TEST_CASE_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE tsav JOIN TEST_CASE_UI_ELEMENT_GROUP_STEP tcsf ON tsav.TEST_CASE_UI_ELEMENT_GROUP_STEP_UUID = tcsf.TEST_CASE_UI_ELEMENT_GROUP_STEP_UUID JOIN TEST_CASE_STEP tcs ON tcsf.TEST_CASE_STEP_UUID = tcs.TEST_CASE_STEP_UUID JOIN TEST_CASE tc ON tcs.TEST_CASE_UUID = tc.TEST_CASE_UUID JOIN TEST_SET ts ON tcs.TEST_SET_UUID = ts.TEST_SET_UUID JOIN UI_ELEMENT_GROUP ug ON tcsf.UI_ELEMENT_GROUP_UUID = ug.UI_ELEMENT_GROUP_UUID JOIN info_tenant.PRE_DEFINED_VALUES pd ON tsav.PRE_DEFINED_VALUES_UUID = pd.PRE_DEFINED_VALUES_UUID JOIN DATA_ELEMENT de ON pd.CODE_SET_UUID = de.CODE_SET_UUID ) as test where FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID AND test.DATA_ELEMENT_UUID=:DATA_ELEMENT_UUID order by TEST_SET_ID desc, TEST_CASE_ID desc, ID desc`;
    queryData_pre_defined = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  }
  if (input && input.FUNCTION_GRID_DE == 'DATA_ELEMENT_CHILD_FUNCTION_STEP') {
    const selectQuery = `select * from ( SELECT FUNCTION_STEP_ID as ID, concat( FUNCTION_STEP_ID, ' - ', FUNCTION_STEP_NAME ) as ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, de.DATA_ELEMENT_UUID, concat( f.FUNCTION_ID, ' - ', f.FUNCTION_NAME ) as FUNCTION_UUID, fs.FUNCTIONAL_AREA_UUID, f.FUNCTION_ID, '' as PARENT_GROUP FROM FUNCTION_STEP_ATTRIBUTE_VALUE tsav, FUNCTION_STEP fs, featuremanagement_app.FUNCTION f ,info_tenant.PRE_DEFINED_VALUES pd,DATA_ELEMENT de where fs.FUNCTION_UUID = f.FUNCTION_UUID and tsav.FUNCTION_STEP_UUID = fs.FUNCTION_STEP_UUID and tsav.PRE_DEFINED_VALUES_UUID=pd.PRE_DEFINED_VALUES_UUID and pd.CODE_SET_UUID=de.CODE_SET_UUID union all select FUNCTION_UI_ELEMENT_GROUP_STEP_ID as ID, concat( FUNCTION_UI_ELEMENT_GROUP_STEP_ID, ' - ', FUNCTION_UI_ELEMENT_GROUP_STEP_NAME ) as ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, de.DATA_ELEMENT_UUID, concat( f.FUNCTION_ID, ' - ', f.FUNCTION_NAME ) as FUNCTION_UUID, fs.FUNCTIONAL_AREA_UUID, f.FUNCTION_ID, concat( ug.UI_ELEMENT_GROUP_ID, ' - ', ug.UI_ELEMENT_GROUP_NAME, ' - UI Element Group' ) as PARENT_GROUP from FUNCTION_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE tsav, FUNCTION_UI_ELEMENT_GROUP_STEP fs, featuremanagement_app.FUNCTION f, UI_ELEMENT_GROUP ug ,info_tenant.PRE_DEFINED_VALUES pd,DATA_ELEMENT de where fs.FUNCTION_UUID = f.FUNCTION_UUID and fs.UI_ELEMENT_GROUP_UUID = ug.UI_ELEMENT_GROUP_UUID and tsav.FUNCTION_UI_ELEMENT_GROUP_STEP_UUID = fs.FUNCTION_UI_ELEMENT_GROUP_STEP_UUID and tsav.PRE_DEFINED_VALUES_UUID=pd.PRE_DEFINED_VALUES_UUID and pd.CODE_SET_UUID=de.CODE_SET_UUID ) as test where FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID and test.DATA_ELEMENT_UUID=:DATA_ELEMENT_UUID order by FUNCTION_ID desc, ID desc`;
    queryData_pre_defined = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  }
  if (input && input.UI_ELEMENT_GRID_DE == 'DATA_ELEMENT_CHILD_UI_ELEMENT') {
    const selectQuery = `SELECT UI_ELEMENT_GROUP_STEP_ID as ID, concat( UI_ELEMENT_GROUP_STEP_ID, ' - ', UI_ELEMENT_GROUP_STEP_NAME ) as ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, de.DATA_ELEMENT_UUID, concat( uig.UI_ELEMENT_GROUP_ID, ' - ', uig.UI_ELEMENT_GROUP_NAME ) as UI_ELEMENT_GROUP_UUID FROM UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE tsav, UI_ELEMENT_GROUP_STEP uis, UI_ELEMENT_GROUP uig,info_tenant.PRE_DEFINED_VALUES pd,DATA_ELEMENT de where uis.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID and uis.UI_ELEMENT_GROUP_UUID = uig.UI_ELEMENT_GROUP_UUID and tsav.UI_ELEMENT_GROUP_STEP_UUID = uis.UI_ELEMENT_GROUP_STEP_UUID and tsav.PRE_DEFINED_VALUES_UUID=pd.PRE_DEFINED_VALUES_UUID and pd.CODE_SET_UUID=de.CODE_SET_UUID and de.DATA_ELEMENT_UUID=:DATA_ELEMENT_UUID order by UI_ELEMENT_GROUP_ID desc, ID desc`;
    queryData_pre_defined = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  }
  if (input && input.TEST_CASE_GRID == 'PRE_DEFINED_CHILD_TEST_CASE_STEP') {
    const selectQuery = `select DISTINCT * from ( SELECT TEST_CASE_STEP_ID as ID,concat(TEST_CASE_STEP_ID,' - ',TEST_CASE_STEP_NAME) as ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, concat( tc.TEST_CASE_ID, ' - ', tc.TEST_CASE_NAME ) as TEST_CASE_UUID, concat( ts.TEST_SET_ID, ' - ', ts.TEST_SET_NAME ) as TEST_SET_UUID, tcs.FUNCTIONAL_AREA_UUID, tc.TEST_CASE_ID, ts.TEST_SET_ID, '' as PARENT_GROUP FROM TEST_CASE_STEP_ATTRIBUTE_VALUE tsav, TEST_CASE_STEP tcs, TEST_CASE tc, TEST_SET ts where tcs.TEST_CASE_UUID = tc.TEST_CASE_UUID and tcs.TEST_SET_UUID = ts.TEST_SET_UUID and tsav.TEST_CASE_STEP_UUID=tcs.TEST_CASE_STEP_UUID union all select TEST_CASE_FUNCTION_STEP_ID as ID, concat(TEST_CASE_FUNCTION_STEP_ID,' - ',TEST_CASE_FUNCTION_STEP_NAME) as ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, concat( tc.TEST_CASE_ID, ' - ', tc.TEST_CASE_NAME ) as TEST_CASE_UUID, concat( ts.TEST_SET_ID, ' - ', ts.TEST_SET_NAME ) as TEST_SET_UUID, tcsf.FUNCTIONAL_AREA_UUID, tc.TEST_CASE_ID, ts.TEST_SET_ID, concat( FUNCTION_ID, ' - ', FUNCTION_NAME, ' - Function' ) as PARENT_GROUP from TEST_CASE_FUNCTION_STEP_ATTRIBUTE_VALUE tsav, TEST_CASE_FUNCTION_STEP tcsf, TEST_CASE_STEP tcs, TEST_CASE tc, TEST_SET ts, featuremanagement_app.FUNCTION f WHERE tcsf.TEST_CASE_STEP_UUID = tcs.TEST_CASE_STEP_UUID AND tcs.TEST_CASE_UUID = tc.TEST_CASE_UUID and tcs.TEST_SET_UUID = ts.TEST_SET_UUID and tcsf.FUNCTION_UUID = f.FUNCTION_UUID and tsav.TEST_CASE_FUNCTION_STEP_UUID=tcsf.TEST_CASE_FUNCTION_STEP_UUID union all select TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_ID as ID,concat(TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_ID,' - ',TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_NAME) as ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, concat( tc.TEST_CASE_ID, ' - ', tc.TEST_CASE_NAME ) as TEST_CASE_UUID, concat( ts.TEST_SET_ID, ' - ', ts.TEST_SET_NAME ) as TEST_SET_UUID, tcsf.FUNCTIONAL_AREA_UUID, tc.TEST_CASE_ID, ts.TEST_SET_ID, concat( ug.UI_ELEMENT_GROUP_ID, ' - ', ug.UI_ELEMENT_GROUP_NAME, ' - UI Element Group' ) as PARENT_GROUP from TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE tsav, TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP tcsf, TEST_CASE_STEP tcs, TEST_CASE tc, TEST_SET ts, UI_ELEMENT_GROUP ug WHERE tcsf.TEST_CASE_STEP_UUID = tcs.TEST_CASE_STEP_UUID AND tcs.TEST_CASE_UUID = tc.TEST_CASE_UUID and tcs.TEST_SET_UUID = ts.TEST_SET_UUID and tcsf.UI_ELEMENT_GROUP_UUID = ug.UI_ELEMENT_GROUP_UUID and tsav.TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_UUID=tcsf.TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_UUID union all select TEST_CASE_UI_ELEMENT_GROUP_STEP_ID as ID,concat(TEST_CASE_UI_ELEMENT_GROUP_STEP_ID,' - ',TEST_CASE_UI_ELEMENT_GROUP_STEP_NAME) as ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, concat( tc.TEST_CASE_ID, ' - ', tc.TEST_CASE_NAME ) as TEST_CASE_UUID, concat( ts.TEST_SET_ID, ' - ', ts.TEST_SET_NAME ) as TEST_SET_UUID, tcsf.FUNCTIONAL_AREA_UUID, tc.TEST_CASE_ID, ts.TEST_SET_ID, concat( ug.UI_ELEMENT_GROUP_ID, ' - ', ug.UI_ELEMENT_GROUP_NAME, ' - UI Element Group' ) as PARENT_GROUP from TEST_CASE_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE tsav, TEST_CASE_UI_ELEMENT_GROUP_STEP tcsf, TEST_CASE_STEP tcs, TEST_CASE tc, TEST_SET ts, UI_ELEMENT_GROUP ug WHERE tcsf.TEST_CASE_STEP_UUID = tcs.TEST_CASE_STEP_UUID AND tcs.TEST_CASE_UUID = tc.TEST_CASE_UUID and tcs.TEST_SET_UUID = ts.TEST_SET_UUID and tcsf.UI_ELEMENT_GROUP_UUID = ug.UI_ELEMENT_GROUP_UUID and tsav.TEST_CASE_UI_ELEMENT_GROUP_STEP_UUID=tcsf.TEST_CASE_UI_ELEMENT_GROUP_STEP_UUID ) as test where FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID and test.PRE_DEFINED_VALUES_UUID=:PRE_DEFINED_VALUES_UUID order by TEST_SET_ID desc, TEST_CASE_ID desc, ID desc`;
    queryData_pre_defined = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  }
  if (input && input.FUNCTION_GRID == 'PRE_DEFINED_CHILD_FUNCTION_STEP') {
    const selectQuery = `select DISTINCT * from ( SELECT FUNCTION_STEP_ID as ID,concat(FUNCTION_STEP_ID,' - ',FUNCTION_STEP_NAME) as ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, concat( f.FUNCTION_ID, ' - ', f.FUNCTION_NAME ) as FUNCTION_UUID, fs.FUNCTIONAL_AREA_UUID, f.FUNCTION_ID, '' as PARENT_GROUP FROM FUNCTION_STEP_ATTRIBUTE_VALUE tsav, FUNCTION_STEP fs, featuremanagement_app.FUNCTION f where fs.FUNCTION_UUID = f.FUNCTION_UUID and tsav.FUNCTION_STEP_UUID=fs.FUNCTION_STEP_UUID union all select FUNCTION_UI_ELEMENT_GROUP_STEP_ID as ID,concat(FUNCTION_UI_ELEMENT_GROUP_STEP_ID,' - ',FUNCTION_UI_ELEMENT_GROUP_STEP_NAME) as ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, concat( f.FUNCTION_ID, ' - ', f.FUNCTION_NAME ) as FUNCTION_UUID, fs.FUNCTIONAL_AREA_UUID, f.FUNCTION_ID, concat( ug.UI_ELEMENT_GROUP_ID, ' - ', ug.UI_ELEMENT_GROUP_NAME, ' - UI Element Group' ) as PARENT_GROUP from FUNCTION_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE tsav, FUNCTION_UI_ELEMENT_GROUP_STEP fs, featuremanagement_app.FUNCTION f, UI_ELEMENT_GROUP ug where fs.FUNCTION_UUID = f.FUNCTION_UUID and fs.UI_ELEMENT_GROUP_UUID = ug.UI_ELEMENT_GROUP_UUID and tsav.FUNCTION_UI_ELEMENT_GROUP_STEP_UUID=fs.FUNCTION_UI_ELEMENT_GROUP_STEP_UUID ) as test where FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID and test.PRE_DEFINED_VALUES_UUID=:PRE_DEFINED_VALUES_UUID order by FUNCTION_ID desc, ID desc`;
    queryData_pre_defined = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  }
  if (input && input.UI_ELEMENT_GRID == 'PRE_DEFINED_CHILD_UI_ELEMENT') {
    const selectQuery = `SELECT UI_ELEMENT_GROUP_STEP_ID as ID,concat(UI_ELEMENT_GROUP_STEP_ID,' - ', UI_ELEMENT_GROUP_STEP_NAME) as ATTRIBUTE_KEY, tsav.PRE_DEFINED_VALUES_UUID, concat( uig.UI_ELEMENT_GROUP_ID, ' - ', uig.UI_ELEMENT_GROUP_NAME ) as UI_ELEMENT_GROUP_UUID FROM UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE tsav, UI_ELEMENT_GROUP_STEP uis, UI_ELEMENT_GROUP uig where uis.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID and uis.UI_ELEMENT_GROUP_UUID = uig.UI_ELEMENT_GROUP_UUID and tsav.UI_ELEMENT_GROUP_STEP_UUID=uis.UI_ELEMENT_GROUP_STEP_UUID and tsav.PRE_DEFINED_VALUES_UUID=:PRE_DEFINED_VALUES_UUID order by UI_ELEMENT_GROUP_ID desc, ID desc`;
    queryData_pre_defined = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  }
  if (input && input.FIRST_GRID == 'TEST_CASE_STEP_TAB') {
    const selectQuery = `select * from ( SELECT TEST_CASE_STEP_ID as ID, 'TEST_CASE_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_STEP_UUID' as PRIMARY_COLUMN_NAME, TEST_CASE_STEP_UUID as PRIMARY_COLUMN_VALUE, tcs.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, concat( tc.TEST_CASE_ID, ' - ', tc.TEST_CASE_NAME ) as TEST_CASE_UUID, concat( ts.TEST_SET_ID, ' - ', ts.TEST_SET_NAME ) as TEST_SET_UUID, tcs.FUNCTIONAL_AREA_UUID, tc.TEST_CASE_ID, ts.TEST_SET_ID, '' as PARENT_GROUP FROM TEST_CASE_STEP tcs, TEST_CASE tc, TEST_SET ts where tcs.TEST_CASE_UUID = tc.TEST_CASE_UUID and tcs.TEST_SET_UUID = ts.TEST_SET_UUID union all select TEST_CASE_FUNCTION_STEP_ID as ID, 'TEST_CASE_FUNCTION_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_FUNCTION_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_FUNCTION_STEP_UUID' as PRIMARY_COLUMN_NAME, TEST_CASE_FUNCTION_STEP_UUID as PRIMARY_COLUMN_VALUE, tcsf.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, concat( tc.TEST_CASE_ID, ' - ', tc.TEST_CASE_NAME ) as TEST_CASE_UUID, concat( ts.TEST_SET_ID, ' - ', ts.TEST_SET_NAME ) as TEST_SET_UUID, tcsf.FUNCTIONAL_AREA_UUID, tc.TEST_CASE_ID, ts.TEST_SET_ID, concat( FUNCTION_ID, ' - ', FUNCTION_NAME, ' - Function' ) as PARENT_GROUP from TEST_CASE_FUNCTION_STEP tcsf, TEST_CASE_STEP tcs, TEST_CASE tc, TEST_SET ts, featuremanagement_app.FUNCTION f WHERE tcsf.TEST_CASE_STEP_UUID = tcs.TEST_CASE_STEP_UUID AND tcs.TEST_CASE_UUID = tc.TEST_CASE_UUID and tcs.TEST_SET_UUID = ts.TEST_SET_UUID and tcsf.FUNCTION_UUID = f.FUNCTION_UUID union all select TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_ID as ID, 'TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_UUID' as PRIMARY_COLUMN_NAME, TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_UUID as PRIMARY_COLUMN_VALUE, tcsf.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, concat( tc.TEST_CASE_ID, ' - ', tc.TEST_CASE_NAME ) as TEST_CASE_UUID, concat( ts.TEST_SET_ID, ' - ', ts.TEST_SET_NAME ) as TEST_SET_UUID, tcsf.FUNCTIONAL_AREA_UUID, tc.TEST_CASE_ID, ts.TEST_SET_ID, concat( ug.UI_ELEMENT_GROUP_ID, ' - ', ug.UI_ELEMENT_GROUP_NAME, ' - UI Element Group' ) as PARENT_GROUP from TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP tcsf, TEST_CASE_STEP tcs, TEST_CASE tc, TEST_SET ts, UI_ELEMENT_GROUP ug WHERE tcsf.TEST_CASE_STEP_UUID = tcs.TEST_CASE_STEP_UUID AND tcs.TEST_CASE_UUID = tc.TEST_CASE_UUID and tcs.TEST_SET_UUID = ts.TEST_SET_UUID and tcsf.UI_ELEMENT_GROUP_UUID = ug.UI_ELEMENT_GROUP_UUID union all select TEST_CASE_UI_ELEMENT_GROUP_STEP_ID as ID, 'TEST_CASE_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_UI_ELEMENT_GROUP_STEP_UUID' as PRIMARY_COLUMN_NAME, TEST_CASE_UI_ELEMENT_GROUP_STEP_UUID as PRIMARY_COLUMN_VALUE, tcsf.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, concat( tc.TEST_CASE_ID, ' - ', tc.TEST_CASE_NAME ) as TEST_CASE_UUID, concat( ts.TEST_SET_ID, ' - ', ts.TEST_SET_NAME ) as TEST_SET_UUID, tcsf.FUNCTIONAL_AREA_UUID, tc.TEST_CASE_ID, ts.TEST_SET_ID, concat( ug.UI_ELEMENT_GROUP_ID, ' - ', ug.UI_ELEMENT_GROUP_NAME, ' - UI Element Group' ) as PARENT_GROUP from TEST_CASE_UI_ELEMENT_GROUP_STEP tcsf, TEST_CASE_STEP tcs, TEST_CASE tc, TEST_SET ts, UI_ELEMENT_GROUP ug WHERE tcsf.TEST_CASE_STEP_UUID = tcs.TEST_CASE_STEP_UUID AND tcs.TEST_CASE_UUID = tc.TEST_CASE_UUID and tcs.TEST_SET_UUID = ts.TEST_SET_UUID and tcsf.UI_ELEMENT_GROUP_UUID = ug.UI_ELEMENT_GROUP_UUID ) as test where FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID and test.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID=:STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID order by TEST_SET_ID desc, TEST_CASE_ID desc, ID desc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.SECOND_GRID == 'FUNCTION_STEP_TAB') {
    const selectQuery = `select * from ( SELECT FUNCTION_STEP_ID as ID, 'FUNCTION_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'FUNCTION_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'FUNCTION_STEP_UUID' as PRIMARY_COLUMN_NAME, FUNCTION_STEP_UUID as PRIMARY_COLUMN_VALUE, fs.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, concat( f.FUNCTION_ID, ' - ', f.FUNCTION_NAME ) as FUNCTION_UUID, fs.FUNCTIONAL_AREA_UUID, f.FUNCTION_ID, '' as PARENT_GROUP FROM FUNCTION_STEP fs, featuremanagement_app.FUNCTION f where fs.FUNCTION_UUID = f.FUNCTION_UUID union all select FUNCTION_UI_ELEMENT_GROUP_STEP_ID as ID, 'FUNCTION_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'FUNCTION_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'FUNCTION_UI_ELEMENT_GROUP_STEP_UUID' as PRIMARY_COLUMN_NAME, FUNCTION_UI_ELEMENT_GROUP_STEP_UUID as PRIMARY_COLUMN_VALUE, fs.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, concat( f.FUNCTION_ID, ' - ', f.FUNCTION_NAME ) as FUNCTION_UUID, fs.FUNCTIONAL_AREA_UUID, f.FUNCTION_ID, concat( ug.UI_ELEMENT_GROUP_ID, ' - ', ug.UI_ELEMENT_GROUP_NAME, ' - UI Element Group' ) as PARENT_GROUP from FUNCTION_UI_ELEMENT_GROUP_STEP fs, featuremanagement_app.FUNCTION f, UI_ELEMENT_GROUP ug where fs.FUNCTION_UUID = f.FUNCTION_UUID and fs.UI_ELEMENT_GROUP_UUID = ug.UI_ELEMENT_GROUP_UUID ) as test where FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID and test.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID=:STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID order by FUNCTION_ID desc, ID desc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.THIRD_GRID == 'UI_ELEMENT_GROUP_STEP_TAB') {
    const selectQuery = `SELECT UI_ELEMENT_GROUP_STEP_ID as ID, 'UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'UI_ELEMENT_GROUP_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'UI_ELEMENT_GROUP_STEP_UUID' as PRIMARY_COLUMN_NAME, UI_ELEMENT_GROUP_STEP_UUID as PRIMARY_COLUMN_VALUE, uis.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, concat( uig.UI_ELEMENT_GROUP_ID, ' - ', uig.UI_ELEMENT_GROUP_NAME ) as UI_ELEMENT_GROUP_UUID FROM UI_ELEMENT_GROUP_STEP uis, UI_ELEMENT_GROUP uig where uis.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID and uis.UI_ELEMENT_GROUP_UUID = uig.UI_ELEMENT_GROUP_UUID and uis.STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID=:STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID order by UI_ELEMENT_GROUP_ID desc, ID desc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.FOURTH_GRID == 'NAVIGATION_STEP_TAB') {
    const selectQuery = `SELECT VIEW_NAVIGATION_STEP_ID as ID, 'VIEW_NAVIGATION_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'VIEW_NAVIGATION_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'VIEW_NAVIGATION_STEP_UUID' as PRIMARY_COLUMN_NAME, VIEW_NAVIGATION_STEP_UUID as PRIMARY_COLUMN_VALUE, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, VIEW_NAVIGATION_STEP_TYPE as NAVIGATION_TYPE, concat(PAGE_ID, ' - ', PAGE_NAME) as PAGE_NAME, concat(VIEW_ID, ' - ', VIEW_NAME) as VIEW_NAME FROM VIEW_NAVIGATION_STEP vns, PAGE pg, PAGE_VIEW pv where vns.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID and vns.CURRENT_PAGE_CONTEXT = pg.PAGE_UUID and vns.VIEW_UUID = pv.VIEW_UUID and STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID=:STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID order by ID desc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.GRID_NAME == 'Test Case') {
    const selectQuery = `SELECT CURRENT_PAGE_CONTEXT as PAGE_NAME,TEST_CASE_STEP_UUID, TEST_CASE_STEP_ID, TEST_CASE_UUID, TEST_SET_UUID, IS_PURE_NAVIGATION_STEP,(Select VIEW_UUID from PAGE_VIEW where PAGE_UUID=CURRENT_PAGE_CONTEXT and IS_DEFAULT_VIEW='Yes') as Page_view_uuid, AE_INSERT_ID, AE_UPDATE_ID, AE_INSERT_TS, AE_UPDATE_TS, AE_TRANSACTION_ID, FUNCTIONAL_AREA_UUID, TEST_CASE_STEP_NAME, CURRENT_PAGE_CONTEXT, PAGE_UUID, VIEW_UUID, PROCESS_UUID, USER_ACTION_UUID, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, TEST_CASE_STEP_SEQ_ID, TEST_CASE_STEP_TYPE, NEXT_PAGE_CONTEXT, IS_UI_ELEMENT_GROUP_STEP, IS_FUNCTION_STEP, 'Test Case Step' as GRID_NAME,PLAYWRITE_STEP_CODE,:TEST_CASE_EXECUTON_TYPE as TEST_CASE_EXECUTON_TYPE,'TEST_CASE_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME,'TEST_CASE_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA,'TEST_CASE_STEP_UUID' as PRIMARY_COLUMN_NAME,TEST_CASE_STEP_UUID as PRIMARY_COLUMN_VALUE FROM TEST_CASE_STEP WHERE FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID and TEST_CASE_UUID=:TEST_CASE_UUID order by TEST_CASE_STEP_SEQ_ID asc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.GRID_NAME == 'UI Element Group') {
    const selectQuery = `SELECT :PAGE_UUID as PAGE_UUID,UI_ELEMENT_GROUP_STEP_UUID, UI_ELEMENT_GROUP_STEP_ID, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, UI_ELEMENT_GROUP_STEP_NAME, UI_ELEMENT_GROUP_UUID, FUNCTIONAL_AREA_UUID, CURRENT_PAGE_CONTEXT, STEP_TYPE, 'UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'UI_ELEMENT_GROUP_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'UI_ELEMENT_GROUP_STEP_UUID' as PRIMARY_COLUMN_NAME, UI_ELEMENT_GROUP_STEP_UUID as PRIMARY_COLUMN_VALUE FROM UI_ELEMENT_GROUP_STEP WHERE UI_ELEMENT_GROUP_UUID=:UI_ELEMENT_GROUP_UUID and FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID ORDER BY UI_ELEMENT_GROUP_STEP_ID asc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (
    input &&
    input.GRID_NAME == 'Test Case Step' &&
    input.IS_UI_ELEMENT_GROUP_STEP == 'Yes' &&
    input.IS_FUNCTION_STEP == 'No'
  ) {
    const selectQuery = `SELECT TEST_CASE_UI_ELEMENT_GROUP_STEP_UUID, TEST_CASE_UI_ELEMENT_GROUP_STEP_ID, TEST_CASE_UI_ELEMENT_GROUP_STEP_NAME, CURRENT_PAGE_CONTEXT as PAGE_NAME, TEST_CASE_UI_ELEMENT_GROUP_STEP_TYPE, 'TEST_CASE_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_UI_ELEMENT_GROUP_STEP_UUID' as PRIMARY_COLUMN_NAME, TEST_CASE_UI_ELEMENT_GROUP_STEP_UUID as PRIMARY_COLUMN_VALUE,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM TEST_CASE_UI_ELEMENT_GROUP_STEP WHERE TEST_CASE_STEP_UUID=:TEST_CASE_STEP_UUID and FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID ORDER BY TEST_CASE_UI_ELEMENT_GROUP_STEP_ID asc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.FIRST_CHILD_GRID_NAME == 'Function Step By Function') {
    const selectQuery = `SELECT CURRENT_PAGE_CONTEXT as PAGE_NAME, FUNCTION_STEP_ID, FUNCTION_STEP_NAME, FUNCTION_STEP_UUID, IS_PURE_NAVIGATION_STEP, ( Select VIEW_UUID from PAGE_VIEW where PAGE_UUID = CURRENT_PAGE_CONTEXT and IS_DEFAULT_VIEW = 'Yes' ) as Page_view_uuid, NEXT_PAGE_CONTEXT, CURRENT_PAGE_CONTEXT, IS_OVERIDE_UI_ELEMENT_VALUE_ALLOWED, IS_UI_ELEMENT_VALUE_ATTRIBUTE_PRESENT, IS_UI_ELEMENT_GROUP_STEP, 'FUNCTION_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'FUNCTION_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'FUNCTION_STEP_UUID' as PRIMARY_COLUMN_NAME, FUNCTION_STEP_UUID as PRIMARY_COLUMN_VALUE, 'Function Step' as GRID_NAME, FUNCTION_STEP_TYPE, API_UUID, IS_API_ATTRIBUTE_VALUE_PRESENT, FUNCTION_STEP_SEQ_ID,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM FUNCTION_STEP WHERE FUNCTION_UUID=:FUNCTION_UUID and FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID ORDER BY FUNCTION_STEP_SEQ_ID asc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.GRID_NAME == 'Function Step') {
    const selectQuery = `SELECT FUNCTION_UI_ELEMENT_GROUP_STEP_UUID, FUNCTION_UI_ELEMENT_GROUP_STEP_ID, FUNCTION_UI_ELEMENT_GROUP_STEP_NAME, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, CURRENT_PAGE_CONTEXT, FUNCTION_UI_ELEMENT_GROUP_STEP_TYPE, FUNCTION_STEP_UUID, FUNCTION_UUID, UI_ELEMENT_GROUP_UUID, FUNCTIONAL_AREA_UUID, 'FUNCTION_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'FUNCTION_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'FUNCTION_UI_ELEMENT_GROUP_STEP_UUID' as PRIMARY_COLUMN_NAME, FUNCTION_UI_ELEMENT_GROUP_STEP_UUID as PRIMARY_COLUMN_VALUE, CURRENT_PAGE_CONTEXT as PAGE_NAME FROM FUNCTION_UI_ELEMENT_GROUP_STEP WHERE FUNCTION_STEP_UUID=:FUNCTION_STEP_UUID and FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID ORDER BY FUNCTION_UI_ELEMENT_GROUP_STEP_ID asc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (
    input &&
    input.GRID_NAME == 'Test Case Step' &&
    input.IS_UI_ELEMENT_GROUP_STEP == 'No' &&
    input.IS_FUNCTION_STEP == 'Yes'
  ) {
    const selectQuery = `SELECT CURRENT_PAGE_CONTEXT as PAGE_NAME, TEST_CASE_FUNCTION_STEP_UUID, TEST_CASE_FUNCTION_STEP_ID, TEST_CASE_FUNCTION_STEP_NAME, IS_PURE_NAVIGATION_STEP, ( Select VIEW_UUID from PAGE_VIEW where PAGE_UUID = CURRENT_PAGE_CONTEXT and IS_DEFAULT_VIEW = 'Yes' ) as Page_view_uuid, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, CURRENT_PAGE_CONTEXT, NEXT_PAGE_CONTEXT, TEST_CASE_FUNCTION_STEP_TYPE, TEST_CASE_FUNCTION_STEP_SEQ_ID, TEST_CASE_STEP_UUID, AE_INSERT_ID, AE_UPDATE_ID, AE_TRANSACTION_ID, AE_INSERT_TS, AE_UPDATE_TS, FUNCTIONAL_AREA_UUID, FUNCTION_UUID, FUNCTION_STEP_UUID, IS_UI_ELEMENT_GROUP_STEP, 'TEST_CASE_FUNCTION_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_FUNCTION_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_FUNCTION_STEP_UUID' as PRIMARY_COLUMN_NAME, TEST_CASE_FUNCTION_STEP_UUID as PRIMARY_COLUMN_VALUE, 'Test Case Function Step' as GRID_NAME FROM TEST_CASE_FUNCTION_STEP WHERE TEST_CASE_STEP_UUID=:TEST_CASE_STEP_UUID and FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID order by TEST_CASE_FUNCTION_STEP_SEQ_ID asc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.GRID_NAME == 'Test Case Function Step') {
    const selectQuery = `SELECT TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_UUID, TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_ID, TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_NAME, CURRENT_PAGE_CONTEXT as PAGE_NAME, 'TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_UUID' as PRIMARY_COLUMN_NAME, TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_UUID as PRIMARY_COLUMN_VALUE, TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_TYPE,STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP where TEST_CASE_FUNCTION_STEP_UUID=:TEST_CASE_FUNCTION_STEP_UUID and FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID ORDER BY TEST_CASE_FUNCTION_UI_ELEMENT_GROUP_STEP_ID asc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.FIRST_CHILD_GRID_NAME == 'Test Case Step By Page') {
    const selectQuery = `Select CONCAT( TEST_SET_ID, ' - ', TEST_SET_NAME ) as TEST_SET_UUID, CONCAT( TEST_CASE_ID, ' - ', TEST_CASE_NAME ) as TEST_CASE_UUID, TEST_CASE_STEP_ID, TEST_CASE_STEP_NAME, 'TEST_CASE_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_STEP_UUID' as PRIMARY_COLUMN_NAME, tsc.TEST_CASE_STEP_UUID as PRIMARY_COLUMN_VALUE, TEST_CASE_STEP_TYPE, NEXT_PAGE_CONTEXT, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID from TEST_CASE_STEP tsc, TEST_SET ts, TEST_CASE tc, TEST_CASE_STEP_ATTRIBUTE_VALUE tcsv where tsc.TEST_CASE_STEP_UUID = tcsv.TEST_CASE_STEP_UUID and tsc.TEST_SET_UUID = ts.TEST_SET_UUID and tsc.TEST_CASE_UUID = tc.TEST_CASE_UUID and tcsv.TEST_CASE_STEP_ATTRIBUTE_DATA=:PAGE_UUID and tsc.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID order by TEST_SET_ID, TEST_CASE_ID, TEST_CASE_STEP_SEQ_ID asc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.SECOND_CHILD_GRID_NAME == 'Test Case Step By UI Element') {
    const selectQuery = `Select CONCAT( TEST_SET_ID, ' - ', TEST_SET_NAME ) as TEST_SET_UUID, CONCAT( TEST_CASE_ID, ' - ', TEST_CASE_NAME ) as TEST_CASE_UUID, TEST_CASE_STEP_ID, TEST_CASE_STEP_NAME, 'TEST_CASE_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_STEP_UUID' as PRIMARY_COLUMN_NAME, tsc.TEST_CASE_STEP_UUID as PRIMARY_COLUMN_VALUE, TEST_CASE_STEP_TYPE, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID from TEST_CASE_STEP tsc, TEST_SET ts, TEST_CASE tc, TEST_CASE_STEP_ATTRIBUTE_VALUE tcsv where tsc.TEST_CASE_STEP_UUID = tcsv.TEST_CASE_STEP_UUID and tsc.TEST_SET_UUID = ts.TEST_SET_UUID and tsc.TEST_CASE_UUID = tc.TEST_CASE_UUID and tcsv.TEST_CASE_STEP_ATTRIBUTE_DATA=:UI_ELEMENT_UUID and tsc.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID order by TEST_CASE_STEP_ID desc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.SECOND_CHILD_GRID_NAME == 'Test Case Step By Function') {
    const selectQuery = `Select CONCAT( TEST_SET_ID, ' - ', TEST_SET_NAME ) as TEST_SET_UUID, CONCAT( TEST_CASE_ID, ' - ', TEST_CASE_NAME ) as TEST_CASE_UUID, TEST_CASE_STEP_ID, TEST_CASE_STEP_TYPE, 'TEST_CASE_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_STEP_UUID' as PRIMARY_COLUMN_NAME, tsc.TEST_CASE_STEP_UUID as PRIMARY_COLUMN_VALUE, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID from TEST_CASE_STEP tsc, TEST_SET ts, TEST_CASE tc, TEST_CASE_STEP_ATTRIBUTE_VALUE tcsv where tsc.TEST_CASE_STEP_UUID = tcsv.TEST_CASE_STEP_UUID and tsc.TEST_SET_UUID = ts.TEST_SET_UUID and tsc.TEST_CASE_UUID = tc.TEST_CASE_UUID and tcsv.TEST_CASE_STEP_ATTRIBUTE_DATA=:FUNCTION_UUID and ts.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID order by TEST_SET_ID, TEST_CASE_ID, TEST_CASE_STEP_ID asc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.SECOND_CHILD_GRID_NAME == 'Function Step Under Page') {
    const selectQuery = `SELECT CONCAT( FUNCTION_ID, ' - ', FUNCTION_NAME ) AS FUNCTION_UUID, '' AS FUNCTION_STEP_ID, '' AS FUNCTION_STEP_NAME, 'FUNCTION_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'FUNCTION_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'FUNCTION_STEP_UUID' as PRIMARY_COLUMN_NAME, '00886379-db02-11ef-ba34-02a48541b261' as PRIMARY_COLUMN_VALUE, '' AS FUNCTIONAL_AREA_UUID, '' AS FUNCTION_STEP_TYPE, '00886379-db02-11ef-ba34-02a48541b261' as STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM featuremanagement_app.FUNCTION WHERE START_PAGE_NAME=:PAGE_UUID AND FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID UNION SELECT CONCAT( f.FUNCTION_ID, ' - ', f.FUNCTION_NAME ) AS FUNCTION_UUID, fs.FUNCTION_STEP_ID, fs.FUNCTION_STEP_NAME, 'FUNCTION_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'FUNCTION_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'FUNCTION_STEP_UUID' as PRIMARY_COLUMN_NAME, FUNCTION_STEP_UUID as PRIMARY_COLUMN_VALUE, fs.FUNCTIONAL_AREA_UUID, fs.FUNCTION_STEP_TYPE , STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM FUNCTION_STEP fs JOIN featuremanagement_app.FUNCTION f ON fs.FUNCTION_UUID = f.FUNCTION_UUID WHERE fs.CURRENT_PAGE_CONTEXT=:PAGE_UUID AND fs.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID ORDER BY FUNCTION_STEP_ID DESC`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.FIRST_CHILD_GRID_NAME == 'Function Step Under UI Element') {
    const selectQuery = `SELECT CONCAT( f.FUNCTION_ID, ' - ', f.FUNCTION_NAME ) AS FUNCTION_UUID, fs.FUNCTION_STEP_ID, fs.FUNCTION_STEP_NAME, 'FUNCTION_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'FUNCTION_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'FUNCTION_STEP_UUID' as PRIMARY_COLUMN_NAME, fs.FUNCTION_STEP_UUID as PRIMARY_COLUMN_VALUE, fs.FUNCTIONAL_AREA_UUID, fs.FUNCTION_STEP_TYPE, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM FUNCTION_STEP fs JOIN featuremanagement_app.FUNCTION f ON fs.FUNCTION_UUID = f.FUNCTION_UUID JOIN FUNCTION_STEP_ATTRIBUTE_VALUE fsa ON fs.FUNCTION_STEP_UUID = fsa.FUNCTION_STEP_UUID WHERE fsa.FUNCTION_STEP_ATTRIBUTE_DATA=:UI_ELEMENT_UUID AND fs.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID ORDER BY FUNCTION_STEP_ID desc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.THIRD_CHILD_GRID_NAME == 'UI Element Group Step Under UI Element') {
    const selectQuery = `SELECT DISTINCT CONCAT( UI_ELEMENT_GROUP_ID, ' - ', UI_ELEMENT_GROUP_NAME ) as UI_ELEMENT_GROUP_UUID, UI_ELEMENT_GROUP_STEP_ID, UI_ELEMENT_GROUP_STEP_NAME, 'UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'UI_ELEMENT_GROUP_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'UI_ELEMENT_GROUP_STEP_UUID' as PRIMARY_COLUMN_NAME, ues.UI_ELEMENT_GROUP_STEP_UUID as PRIMARY_COLUMN_VALUE, STEP_TYPE, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM UI_ELEMENT_GROUP_STEP ues JOIN UI_ELEMENT_GROUP us ON ues.UI_ELEMENT_GROUP_UUID = us.UI_ELEMENT_GROUP_UUID JOIN UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE ueas ON ues.UI_ELEMENT_GROUP_STEP_UUID = ueas.UI_ELEMENT_GROUP_STEP_UUID WHERE ues.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID AND ueas.UI_ELEMENT_GROUP_STEP_ATTRIBUTE_DATA=:UI_ELEMENT_UUID ORDER BY UI_ELEMENT_GROUP_STEP_ID desc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.THIRD_CHILD_GRID_NAME == 'UI Element Group Step Under Page') {
    const selectQuery = `SELECT DISTINCT CONCAT( UI_ELEMENT_GROUP_ID, ' - ', UI_ELEMENT_GROUP_NAME ) as UI_ELEMENT_GROUP_UUID, '' as UI_ELEMENT_GROUP_STEP_ID, '' as UI_ELEMENT_GROUP_STEP_NAME, 'UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'UI_ELEMENT_GROUP_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'UI_ELEMENT_GROUP_STEP_UUID' as PRIMARY_COLUMN_NAME, '00886379-db02-11ef-ba34-02a48541b261' as PRIMARY_COLUMN_VALUE, '' as STEP_TYPE, '00886379-db02-11ef-ba34-02a48541b261' as STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM UI_ELEMENT_GROUP WHERE FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID AND PAGE_UUID=:PAGE_UUID UNION SELECT DISTINCT CONCAT( us.UI_ELEMENT_GROUP_ID, ' - ', us.UI_ELEMENT_GROUP_NAME ) as UI_ELEMENT_GROUP_UUID, ues.UI_ELEMENT_GROUP_STEP_ID, ues.UI_ELEMENT_GROUP_STEP_NAME, 'UI_ELEMENT_GROUP_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'UI_ELEMENT_GROUP_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'UI_ELEMENT_GROUP_STEP_UUID' as PRIMARY_COLUMN_NAME, UI_ELEMENT_GROUP_STEP_UUID as PRIMARY_COLUMN_VALUE, ues.STEP_TYPE, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM UI_ELEMENT_GROUP_STEP ues JOIN UI_ELEMENT_GROUP us ON ues.UI_ELEMENT_GROUP_UUID = us.UI_ELEMENT_GROUP_UUID WHERE ues.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID AND ues.CURRENT_PAGE_CONTEXT=:PAGE_UUID ORDER BY UI_ELEMENT_GROUP_STEP_ID DESC`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.SECOND_CHILD_GRID_NAME == 'Test Case Step Under API') {
    const selectQuery = `Select CONCAT( TEST_SET_ID, ' - ', TEST_SET_NAME ) as TEST_SET_UUID, CONCAT( TEST_CASE_ID, ' - ', TEST_CASE_NAME ) as TEST_CASE_UUID, TEST_CASE_STEP_ID, TEST_CASE_STEP_NAME, 'TEST_CASE_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_STEP_UUID' as PRIMARY_COLUMN_NAME, TEST_CASE_STEP_UUID as PRIMARY_COLUMN_VALUE, TEST_CASE_STEP_TYPE, NEXT_PAGE_CONTEXT, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID from TEST_CASE_STEP tsc, TEST_SET ts, TEST_CASE tc where tsc.TEST_SET_UUID = ts.TEST_SET_UUID and tsc.TEST_CASE_UUID = tc.TEST_CASE_UUID and tsc.API_UUID=:API_UUID and tsc.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID order by TEST_SET_ID, TEST_CASE_ID, TEST_CASE_STEP_SEQ_ID asc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.FIRST_CHILD_GRID_NAME == 'Test Case Step Under API Attribute') {
    const selectQuery = `Select CONCAT( TEST_SET_ID, ' - ', TEST_SET_NAME ) as TEST_SET_UUID, CONCAT( TEST_CASE_ID, ' - ', TEST_CASE_NAME ) as TEST_CASE_UUID, TEST_CASE_STEP_ID, TEST_CASE_STEP_NAME, 'TEST_CASE_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'TEST_CASE_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'TEST_CASE_STEP_UUID' as PRIMARY_COLUMN_NAME, tsc.TEST_CASE_STEP_UUID as PRIMARY_COLUMN_VALUE, TEST_CASE_STEP_TYPE, NEXT_PAGE_CONTEXT, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID from TEST_CASE_STEP tsc, TEST_SET ts, TEST_CASE tc, TEST_CASE_STEP_ATTRIBUTE_VALUE tcsv where tsc.TEST_CASE_STEP_UUID = tcsv.TEST_CASE_STEP_UUID and tsc.TEST_SET_UUID = ts.TEST_SET_UUID and tsc.TEST_CASE_UUID = tc.TEST_CASE_UUID and tcsv.TEST_CASE_STEP_ATTRIBUTE_DATA=:API_ATTRIBUTE_UUID and tsc.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID order by TEST_SET_ID, TEST_CASE_ID, TEST_CASE_STEP_SEQ_ID asc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.THIRD_CHILD_GRID_NAME == 'Function Step Under API') {
    const selectQuery = `SELECT CONCAT( FUNCTION_ID, ' - ', FUNCTION_NAME ) AS FUNCTION_UUID, '' AS FUNCTION_STEP_ID, '' AS FUNCTION_STEP_NAME, 'FUNCTION_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'FUNCTION_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'FUNCTION_STEP_UUID' as PRIMARY_COLUMN_NAME, '00886379-db02-11ef-ba34-02a48541b261' as PRIMARY_COLUMN_VALUE, '' AS FUNCTIONAL_AREA_UUID, '' AS FUNCTION_STEP_TYPE, '00886379-db02-11ef-ba34-02a48541b261' as STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM featuremanagement_app.FUNCTION WHERE START_PAGE_NAME=:PAGE_UUID AND FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID UNION SELECT CONCAT( f.FUNCTION_ID, ' - ', f.FUNCTION_NAME ) AS FUNCTION_UUID, fs.FUNCTION_STEP_ID, fs.FUNCTION_STEP_NAME, 'FUNCTION_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'FUNCTION_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'FUNCTION_STEP_UUID' as PRIMARY_COLUMN_NAME, FUNCTION_STEP_UUID as PRIMARY_COLUMN_VALUE, fs.FUNCTIONAL_AREA_UUID, fs.FUNCTION_STEP_TYPE, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM FUNCTION_STEP fs JOIN featuremanagement_app.FUNCTION f ON fs.FUNCTION_UUID = f.FUNCTION_UUID WHERE fs.API_UUID=:API_UUID AND fs.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID AND fs.IS_API_ATTRIBUTE_VALUE_PRESENT is null ORDER BY FUNCTION_STEP_ID DESC`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.SECOND_CHILD_GRID_NAME == 'Function Step Under API Attribute') {
    const selectQuery = `SELECT CONCAT( f.FUNCTION_ID, ' - ', f.FUNCTION_NAME ) AS FUNCTION_UUID, fs.FUNCTION_STEP_ID, fs.FUNCTION_STEP_NAME, 'FUNCTION_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'FUNCTION_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'FUNCTION_STEP_UUID' as PRIMARY_COLUMN_NAME, fs.FUNCTION_STEP_UUID as PRIMARY_COLUMN_VALUE, fs.FUNCTIONAL_AREA_UUID, fs.FUNCTION_STEP_TYPE, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID FROM FUNCTION_STEP fs JOIN featuremanagement_app.FUNCTION f ON fs.FUNCTION_UUID = f.FUNCTION_UUID JOIN FUNCTION_STEP_ATTRIBUTE_VALUE fsa ON fs.FUNCTION_STEP_UUID = fsa.FUNCTION_STEP_UUID WHERE fsa.FUNCTION_STEP_ATTRIBUTE_DATA=:API_ATTRIBUTE_UUID AND fs.FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID ORDER BY FUNCTION_STEP_ID desc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  } else if (input && input.GRID_NAME == 'View Navigation Step By View Navigation') {
    const selectQuery = `SELECT VIEW_NAVIGATION_STEP_UUID, VIEW_NAVIGATION_STEP_ID, VIEW_NAVIGATION_STEP_NAME, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, VIEW_NAVIGATION_STEP_TYPE, VIEW_NAVIGATION_STEP_SEQ_ID, CURRENT_PAGE_CONTEXT, NEXT_PAGE_CONTEXT, 'VIEW_NAVIGATION_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'VIEW_NAVIGATION_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'VIEW_NAVIGATION_STEP_UUID' as PRIMARY_COLUMN_NAME, VIEW_NAVIGATION_STEP_UUID as PRIMARY_COLUMN_VALUE, VIEW_UUID, 'No' as IS_PURE_NAVIGATION_STEP FROM VIEW_NAVIGATION_STEP WHERE VIEW_UUID=:VIEW_UUID AND FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID ORDER BY VIEW_NAVIGATION_STEP_SEQ_ID asc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  }
  if (input && input.IS_PURE_NAVIGATION_STEP == 'Yes' && input.VIEW_UUID != null) {
    const selectQuery = `SELECT VIEW_NAVIGATION_STEP_UUID, VIEW_NAVIGATION_STEP_ID, VIEW_NAVIGATION_STEP_NAME, STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID, VIEW_NAVIGATION_STEP_TYPE, VIEW_NAVIGATION_STEP_SEQ_ID, CURRENT_PAGE_CONTEXT, NEXT_PAGE_CONTEXT, 'VIEW_NAVIGATION_STEP_ATTRIBUTE_VALUE' as CHILD_ATTRIBUTE_TABLE_NAME, 'VIEW_NAVIGATION_STEP_ATTRIBUTE_DATA' as CHILD_ATTRIBUTE_DATA, 'VIEW_NAVIGATION_STEP_UUID' as PRIMARY_COLUMN_NAME, VIEW_NAVIGATION_STEP_UUID as PRIMARY_COLUMN_VALUE, VIEW_UUID,:IS_PURE_NAVIGATION_STEP as IS_PURE_NAVIGATION_STEP FROM VIEW_NAVIGATION_STEP WHERE VIEW_UUID=:VIEW_UUID AND FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID ORDER BY VIEW_NAVIGATION_STEP_SEQ_ID asc`;
    queryData = await serviceOrchestrator.selectRecordsUsingQuery(`PRIMARYSPRINGFM`, selectQuery, input);
  }
  for (let data of queryData) {
    if (data && Object.keys(data).length) {
      const stepDefAttributeQuery = `SELECT * FROM STEP_DEFINITION_ATTRIBUTE where STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID='${data['STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID']}' order by STEP_DEFINITION_ATTRIBUTE_ID asc`;
      let stepDefAttributeQueryData = await serviceOrchestrator.selectRecordsUsingQuery(
        'PRIMARYSPRINGFM',
        stepDefAttributeQuery,
        input
      );
      const stepDefTemplateVerbiageQuery = `SELECT STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME FROM STEP_DEFINITION_TEMPLATE_VERBIAGE where STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID='${data['STEP_DEFINITION_TEMPLATE_VERBIAGE_UUID']}'`;
      let stepDefTemplateVerbiageQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
        `PRIMARYSPRINGFM`,
        stepDefTemplateVerbiageQuery,
        input
      );
      let stepDefTemplateVerbiageName = stepDefTemplateVerbiageQueryData['STEP_DEFINITION_TEMPLATE_VERBIAGE_NAME'];
      if (stepDefAttributeQueryData && stepDefAttributeQueryData.length) {
        let getUIElementStepDefAttributeUUID = stepDefAttributeQueryData.filter(
          (item) => item['STEP_DEFINITION_ATTRIBUTE_MASTER_UUID'] == 'adcf6e25-f890-476c-bdcf-e723c6d7894c'
        );
        let stepDefArrributeIdforUIElement = '';
        if (getUIElementStepDefAttributeUUID && getUIElementStepDefAttributeUUID.length) {
          stepDefArrributeIdforUIElement = getUIElementStepDefAttributeUUID[0]['STEP_DEFINITION_ATTRIBUTE_UUID'];
        }
        const attributeValueQuery = `SELECT * FROM ${data['CHILD_ATTRIBUTE_TABLE_NAME']} WHERE ${data['PRIMARY_COLUMN_NAME']}='${data['PRIMARY_COLUMN_VALUE']}' and FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID`;
        let attributeValueQueryData = await serviceOrchestrator.selectRecordsUsingQuery(
          'PRIMARYSPRINGFM',
          attributeValueQuery,
          input
        );
        let actualUIElementUUID = '';
        let getUIElementIdFromAttribute = attributeValueQueryData.filter(
          (item) => item['STEP_DEFINITION_ATTRIBUTE_UUID'] == stepDefArrributeIdforUIElement
        );
        if (getUIElementIdFromAttribute && getUIElementIdFromAttribute.length) {
          actualUIElementUUID = getUIElementIdFromAttribute[0][data['CHILD_ATTRIBUTE_DATA']];
        }
        let isDataElementNameTypePassword = false;
        let isDataElementName1TypePassword = false;
        for (let codeDesc of stepDefAttributeQueryData) {
          switch (codeDesc['STEP_DEFINITION_ATTRIBUTE_MASTER_UUID']) {
            case '57b76ab3-8112-4343-af0f-49643c808bf7':
              {
                let pageName = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                const pageNewQuery = `SELECT PAGE_NAME FROM PAGE WHERE PAGE_UUID='${pageName}' AND FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID`;
                let pageNewQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                  `PRIMARYSPRINGFM`,
                  pageNewQuery,
                  input
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll('<Page Name>', function () {
                  return `'` + pageNewQueryData['PAGE_NAME'] + `'`;
                });
              }
              break;
            case 'adcf6e25-f890-476c-bdcf-e723c6d7894c':
              {
                let uiElementName = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                const uiElementQuery = `SELECT UI_ELEMENT_NAME FROM UI_ELEMENT WHERE UI_ELEMENT_UUID='${uiElementName}' AND FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID`;
                let uiElementQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                  `PRIMARYSPRINGFM`,
                  uiElementQuery,
                  input
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll('<UI Element Name>', function () {
                  return `'` + uiElementQueryData['UI_ELEMENT_NAME'] + `'`;
                });
                if (
                  uiElementQueryData['UI_ELEMENT_NAME'] &&
                  uiElementQueryData['UI_ELEMENT_NAME'].toUpperCase() == 'PASSWORD'
                ) {
                  isDataElementNameTypePassword = true;
                }
              }
              break;
            case '7f855066-ad39-4325-8108-30befb2447e6':
              {
                const uiElementTypeQuery = `SELECT * FROM UI_ELEMENT ui,UI_ELEMENT_TYPE_MASTER uit WHERE ui.UI_ELEMENT_TYPE=uit.UI_ELEMENT_TYPE_UUID AND ui.UI_ELEMENT_UUID='${actualUIElementUUID}'`;
                let uiElementTypeQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                  'PRIMARYSPRINGFM',
                  uiElementTypeQuery,
                  input
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll('<UI Element Type>', function () {
                  return `'` + uiElementTypeQueryData['UI_ELEMENT_TYPE_NAME'] + `'`;
                });
              }
              break;
            case '74da67d2-41c9-4cf7-9eea-715243e5fcdc':
              {
                let uiElementValue = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<UI Element Value>',
                  uiElementValue
                    ? function () {
                        if (isDataElementNameTypePassword) {
                          return '********';
                        } else {
                          return `'` + uiElementValue + `'`;
                        }
                      }
                    : `' '`
                );
              }
              break;
            case '235dfa3a-a897-4076-b9bc-ed813ec7c39f':
              {
                let keyNameInKeyPad = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<Key Name in Keypad>',
                  function () {
                    return `'` + keyNameInKeyPad + `'`;
                  }
                );
              }
              break;
            case '005d158d-428c-4bca-ae2d-1c3f9630b549':
              {
                const uiElementQuery = `SELECT * FROM UI_ELEMENT WHERE UI_ELEMENT_UUID='${actualUIElementUUID}'`;
                let uiElementQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                  'PRIMARYSPRINGFM',
                  uiElementQuery,
                  input
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<Event Type>',
                  uiElementQueryData['EVENT_NAME']
                    ? function () {
                        return `'` + uiElementQueryData['EVENT_NAME'] + `'`;
                      }
                    : `' '`
                );
              }
              break;
            case 'afe5f489-b9b3-11ee-a0ed-12e85c8c3755':
              let confirmUIElementValue = getDataFromAttributeValue(
                attributeValueQueryData,
                codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                data['CHILD_ATTRIBUTE_DATA']
              );
              stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                '<Confirm UI Element Value>',
                confirmUIElementValue
                  ? function () {
                      return `'` + confirmUIElementValue + `'`;
                    }
                  : `' '`
              );
              break;
            case '6c698ae8-6305-4bb6-8c23-3a938e7234bd':
              {
                let functionName = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                const functionNameQuery = `SELECT FUNCTION_NAME FROM featuremanagement_app.FUNCTION WHERE FUNCTION_UUID='${functionName}'`;
                let functionNameQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                  `PRIMARYSPRINGFM`,
                  functionNameQuery,
                  input
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll('<Function Name>', function () {
                  return `'` + functionNameQueryData['FUNCTION_NAME'] + `'`;
                });
              }
              break;
            case '2b7e3ad0-f3e4-11ee-9a12-6fc3e771212a':
              {
                let uiElementName1 = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                const uiElementQuery = `SELECT UI_ELEMENT_NAME FROM UI_ELEMENT WHERE UI_ELEMENT_UUID='${uiElementName1}' AND FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID`;
                let uiElementQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                  `PRIMARYSPRINGFM`,
                  uiElementQuery,
                  input
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<UI Element Name 1>',
                  function () {
                    return uiElementQueryData['UI_ELEMENT_NAME']
                      ? `'` + uiElementQueryData['UI_ELEMENT_NAME'] + `'`
                      : `' '`;
                  }
                );
                if (
                  uiElementQueryData['UI_ELEMENT_NAME'] &&
                  uiElementQueryData['UI_ELEMENT_NAME'].toUpperCase() == 'PASSWORD'
                ) {
                  isDataElementName1TypePassword = true;
                }
              }
              break;
            case '3f50ff70-f3e4-11ee-9a12-6fc3e771212a':
              {
                let uiElementValue1 = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<UI Element Value 1>',
                  uiElementValue1
                    ? function () {
                        if (isDataElementName1TypePassword) {
                          return '********';
                        } else {
                          return `'` + uiElementValue1 + `'`;
                        }
                      }
                    : `' '`
                );
              }
              break;
            case '903cf3b0-f8a5-11ee-a163-cdf5a57b7d43':
              {
                let userActionName = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                const uiElementQuery = `SELECT UI_ELEMENT_NAME FROM UI_ELEMENT WHERE UI_ELEMENT_UUID='${userActionName}' AND FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID`;
                let uiElementQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                  `PRIMARYSPRINGFM`,
                  uiElementQuery,
                  input
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll('<User Action Name>', function () {
                  return `'` + uiElementQueryData['UI_ELEMENT_NAME'] + `'`;
                });
              }
              break;
            case '99cf0e40-f8a5-11ee-a163-cdf5a57b7d43':
              {
                const uiElementTypeQuery = `SELECT * FROM UI_ELEMENT ui,UI_ELEMENT_TYPE_MASTER uit WHERE ui.UI_ELEMENT_TYPE=uit.UI_ELEMENT_TYPE_UUID AND ui.UI_ELEMENT_UUID='${actualUIElementUUID}'`;
                let uiElementTypeQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                  'PRIMARYSPRINGFM',
                  uiElementTypeQuery,
                  input
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll('<User Action Type>', function () {
                  return `'` + uiElementTypeQueryData['UI_ELEMENT_TYPE_NAME'] + `'`;
                });
              }
              break;
            case '5c3edc60-f290-11ee-a7a7-c7f3437be2cf':
              {
                let uiElementGroupName = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                let uiElementGroupStepQuery = `SELECT * FROM UI_ELEMENT_GROUP WHERE UI_ELEMENT_GROUP_UUID='${uiElementGroupName}' and FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID`;
                let uiElementGroupStepQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                  'PRIMARYSPRINGFM',
                  uiElementGroupStepQuery,
                  input
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<UI Element Group Name>',
                  function () {
                    return `'` + uiElementGroupStepQueryData['UI_ELEMENT_GROUP_NAME'] + `'`;
                  }
                );
              }
              break;
            case '2dc3a50e-004d-4dec-8270-c7ec5d36cb2c':
              {
                let pageNumber = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<Page Number>',
                  pageNumber
                    ? function () {
                        return `'` + pageNumber + `'`;
                      }
                    : `' '`
                );
              }
              break;
            case 'bca9a7f7-1948-407c-9953-2d01356bbd15':
              {
                let dataKey = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<Data Key>',
                  dataKey
                    ? function () {
                        return `'` + dataKey + `'`;
                      }
                    : `' '`
                );
              }
              break;
            case '3aff7b0e-472c-4393-b6b2-5a61b07cfbff':
              {
                let dataValue = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<Data Value>',
                  dataValue
                    ? function () {
                        return `'` + dataValue + `'`;
                      }
                    : `' '`
                );
              }
              break;
            case 'ceb66327-216f-42fd-845b-9f4543c62baa':
              {
                let fileName = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<File Name>',
                  fileName
                    ? function () {
                        return `'` + fileName + `'`;
                      }
                    : `' '`
                );
              }
              break;
            case 'd20f4347-d4d0-47a1-96f6-190d3b5e4a90':
              {
                let downloadParserName = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<Document Parser Name>',
                  downloadParserName
                    ? function () {
                        return `'` + downloadParserName + `'`;
                      }
                    : `' '`
                );
              }
              break;
            case '36880b70-2e33-11ef-b3ef-e52f192c3af0':
              {
                let apiName = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                const apiQuery = `SELECT API_NAME FROM API_NEW WHERE API_UUID='${apiName}' and FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID`;
                let apiQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                  `PRIMARYSPRINGFM`,
                  apiQuery,
                  input
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll('<API Name>', function () {
                  return `'` + apiQueryData['API_NAME'] + `'`;
                });
              }
              break;
            case '46136260-2e33-11ef-b3ef-e52f192c3af0':
              {
                let apiAttributeName = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                const apiAttributeQuery = `SELECT ATTRIBUTE_NAME FROM API_ATTRIBUTE WHERE API_ATTRIBUTE_UUID='${apiAttributeName}' and FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID`;
                let apiAttributeQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                  `PRIMARYSPRINGFM`,
                  apiAttributeQuery,
                  input
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<API Attribute Name>',
                  function () {
                    return `'` + apiAttributeQueryData['ATTRIBUTE_NAME'] + `'`;
                  }
                );
              }
              break;
            case '7182ebf0-2e33-11ef-9033-4bb93e602d01':
              {
                let apiAttributeValue = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<API Attribute Value>',
                  apiAttributeValue
                    ? function () {
                        return `'` + apiAttributeValue + `'`;
                      }
                    : `' '`
                );
              }
              break;
            case '833eb770-2e33-11ef-9033-4bb93e602d01':
              {
                let responseStatusCode = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<Response Status Code>',
                  responseStatusCode
                    ? function () {
                        return `'` + responseStatusCode + `'`;
                      }
                    : `' '`
                );
              }
              break;
            case 'c53a65a0-613e-11ef-81c7-b59b0b9089cd':
              {
                let pageName1 = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                const pageNewQuery = `SELECT PAGE_NAME FROM PAGE WHERE PAGE_UUID='${pageName1}' AND FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID`;
                let pageNewQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                  `PRIMARYSPRINGFM`,
                  pageNewQuery,
                  input
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll('<Page Name 1>', function () {
                  return `'` + pageNewQueryData['PAGE_NAME'] + `'`;
                });
              }
              break;
            case 'ccd0b030-613e-11ef-81c7-b59b0b9089cd':
              {
                let uiElementState = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<UI Element State>',
                  uiElementState
                    ? function () {
                        return `'` + uiElementState + `'`;
                      }
                    : `' '`
                );
              }
              break;
            case '2afdf3ea-2d25-42c6-ab5e-9f5a6b15e0f8':
              {
                let timeOot = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<Timeout>',
                  timeOot
                    ? function () {
                        return `'` + timeOot + `'`;
                      }
                    : `' '`
                );
              }
              break;
            case '7c7a43c8-e484-11ef-904e-02c8cad0208d':
              {
                let testSetScope = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                let functionIds = getFunctionDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID']
                );
                if (functionIds) {
                  let functionQuery = `SELECT * FROM featuremanagement_app.FUNCTION WHERE FUNCTION_UUID in('${functionIds}') and FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID`;
                  let functionQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                    'PRIMARYSPRINGFM',
                    functionQuery,
                    input
                  );
                  testSetScope = functionQueryData['FUNCTION_NAME'] + ' : ' + testSetScope;
                }
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<Test Set Scope Variable>',
                  testSetScope
                    ? function () {
                        if (isDataElementNameTypePassword) {
                          return '********';
                        } else {
                          return `'` + testSetScope + `'`;
                        }
                      }
                    : `' '`
                );
              }
              break;
            case '842981e7-e484-11ef-904e-02c8cad0208d':
              {
                let testCaseScope = getDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID'],
                  data['CHILD_ATTRIBUTE_DATA']
                );
                let functionIds = getFunctionDataFromAttributeValue(
                  attributeValueQueryData,
                  codeDesc['STEP_DEFINITION_ATTRIBUTE_UUID']
                );
                if (functionIds) {
                  let functionQuery = `SELECT * FROM featuremanagement_app.FUNCTION WHERE FUNCTION_UUID in('${functionIds}') and FUNCTIONAL_AREA_UUID=:APP_LOGGED_IN_FUNTIONAL_AREA_ID`;
                  let functionQueryData = await serviceOrchestrator.selectSingleRecordUsingQuery(
                    'PRIMARYSPRINGFM',
                    functionQuery,
                    input
                  );
                  testCaseScope = functionQueryData['FUNCTION_NAME'] + ' : ' + testCaseScope;
                }
                stepDefTemplateVerbiageName = stepDefTemplateVerbiageName.replaceAll(
                  '<Test Case Scope Variable>',
                  testCaseScope
                    ? function () {
                        if (isDataElementNameTypePassword) {
                          return '********';
                        } else {
                          return `'` + testCaseScope + `'`;
                        }
                      }
                    : `' '`
                );
              }
              break;
          }
        }
      }
      data['ATTRIBUTE_KEYS'] = stepDefTemplateVerbiageName;
      if (input && input.FIRST_CHILD_GRID_NAME == 'Test Case Step By Page') {
        data['ATTRIBUTE_KEY'] = data['TEST_CASE_STEP_ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
      } else if (input && input.FIRST_GRID == 'TEST_CASE_STEP_TAB') {
        data['ATTRIBUTE_KEY'] = data['ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
      } else if (input && input.SECOND_GRID == 'FUNCTION_STEP_TAB') {
        data['ATTRIBUTE_KEY'] = data['ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
      } else if (input && input.THIRD_GRID == 'UI_ELEMENT_GROUP_STEP_TAB') {
        data['ATTRIBUTE_KEY'] = data['ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
      } else if (input && input.FOURTH_GRID == 'NAVIGATION_STEP_TAB') {
        data['ATTRIBUTE_KEY'] = data['ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
      } else if (input && input.SECOND_CHILD_GRID_NAME == 'Test Case Step By UI Element') {
        data['ATTRIBUTE_KEY'] = data['TEST_CASE_STEP_ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
      } else if (input && input.SECOND_CHILD_GRID_NAME == 'Test Case Step By Function') {
        data['ATTRIBUTE_KEY'] = data['TEST_CASE_STEP_ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
      } else if (input && input.SECOND_CHILD_GRID_NAME === 'Function Step Under Page') {
        if (data['FUNCTION_STEP_ID'] && data['ATTRIBUTE_KEYS']) {
          data['ATTRIBUTE_KEY'] = data['FUNCTION_STEP_ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
        } else {
          data['ATTRIBUTE_KEY'] = ' ';
        }
      } else if (input && input.FIRST_CHILD_GRID_NAME == 'Function Step Under UI Element') {
        data['ATTRIBUTE_KEY'] = data['FUNCTION_STEP_ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
      } else if (input && input.THIRD_CHILD_GRID_NAME == 'UI Element Group Step Under UI Element') {
        data['ATTRIBUTE_KEY'] = data['UI_ELEMENT_GROUP_STEP_ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
      } else if (input && input.THIRD_CHILD_GRID_NAME == 'UI Element Group Step Under Page') {
        if (data['UI_ELEMENT_GROUP_STEP_ID'] && data['ATTRIBUTE_KEYS']) {
          data['ATTRIBUTE_KEY'] = data['UI_ELEMENT_GROUP_STEP_ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
        } else {
          data['ATTRIBUTE_KEY'] = ' ';
        }
      } else if (input && input.SECOND_CHILD_GRID_NAME == 'Test Case Step Under API') {
        data['ATTRIBUTE_KEY'] = data['TEST_CASE_STEP_ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
      } else if (input && input.FIRST_CHILD_GRID_NAME == 'Test Case Step Under API Attribute') {
        data['ATTRIBUTE_KEY'] = data['TEST_CASE_STEP_ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
      } else if (input && input.THIRD_CHILD_GRID_NAME === 'Function Step Under API') {
        if (data['FUNCTION_STEP_ID'] && data['ATTRIBUTE_KEYS']) {
          data['ATTRIBUTE_KEY'] = data['FUNCTION_STEP_ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
        } else {
          data['ATTRIBUTE_KEY'] = ' ';
        }
      } else if (input && input.SECOND_CHILD_GRID_NAME == 'Function Step Under API Attribute') {
        data['ATTRIBUTE_KEY'] = data['FUNCTION_STEP_ID'] + ' - ' + data['ATTRIBUTE_KEYS'];
      }
    }
  }
  if (
    input.TEST_CASE_GRID == 'PRE_DEFINED_CHILD_TEST_CASE_STEP' ||
    input.FUNCTION_GRID == 'PRE_DEFINED_CHILD_FUNCTION_STEP' ||
    input.UI_ELEMENT_GRID == 'PRE_DEFINED_CHILD_UI_ELEMENT' ||
    input.TEST_CASE_GRID_DE == 'DATA_ELEMENT_CHILD_TEST_CASE_STEP' ||
    input.FUNCTION_GRID_DE == 'DATA_ELEMENT_CHILD_FUNCTION_STEP' ||
    input.UI_ELEMENT_GRID_DE == 'DATA_ELEMENT_CHILD_UI_ELEMENT'
  ) {
    msg.payload.result = { gridData: queryData_pre_defined };
  } else {
    msg.payload.result = { gridData: queryData };
  }
  node.send(msg);
} catch (error) {
  console.log('Errorr Occured Process and Send Data to ui', error.message);
}
return;
