SELECT DISTINCT
  :PARENT_GRID_NAME AS PARENT_GRID_NAME, 
  'LinkedTestCases' AS LINKED_TEST_CASE_GRID, 
  'AllRequirement' AS ALL_REQ_GRID,
  'TEST_CASE' AS SOURCE_TYPE, 
  'Copy Test Case' AS TEST_CASE_FORM_TYPE,
  'Copy Test Case Steps' AS TEST_CASE_STEP_FORM_TYPE,
  :TEST_SET_NAME AS TEST_SET_NAME,
  tc.TEST_CASE_UUID, 
  tc.TEST_CASE_ID, 
  tc.TEST_CASE_NAME, 
  tc.TEST_CASE_NAME AS US_TEST_CASE_NAME, 
  tc.AE_INSERT_ID, 
  tc.AE_UPDATE_ID, 
  tc.AE_INSERT_TS, 
  tc.AE_UPDATE_TS, 
  tc.AE_TRANSACTION_ID, 
  tc.FUNCTIONAL_AREA_UUID, 
  tc.TEST_SET_UUID, 
  tc.TEST_CASE_SEQ_ID,
  ts.PROCESS_UUID,
  ts.PAGE_UUID,
  ts.VIEW_UUID,
  ts.USER_ACTION_UUID,
  tc.TEST_CASE_STATUS, 
  tc.TEST_CASE_EXECUTON_TYPE,
  tc.ASSOCIATED_VIEW_UUID, 
  'Test Case' AS GRID_NAME,
  tc.SKIP_STEP_WITH_NO_UI_ELEMENT_VALUE,
  tc.USER_STORY_UUID,
  (
    SELECT COUNT(DISTINCT td.TEST_DATA_SET_UUID)+1
    FROM TEST_DATA_SET td
    WHERE td.PARENT_UUID = tc.TEST_CASE_UUID
  ) AS ColumnData,
  tc.TEST_CASE_OWNER
FROM 
  TEST_CASE tc 
  JOIN TEST_SET ts ON tc.TEST_SET_UUID = ts.TEST_SET_UUID
WHERE 
  :PARENT_GRID_NAME = 'User Story Test Set' AND
  tc.USER_STORY_UUID LIKE CONCAT('%', :TEST_SET_USER_STORY_UUID, '%')

UNION

SELECT DISTINCT
  :PARENT_GRID_NAME AS PARENT_GRID_NAME, 
  'LinkedTestCases' AS LINKED_TEST_CASE_GRID, 
  'AllRequirement' AS ALL_REQ_GRID,
  'TEST_CASE' AS SOURCE_TYPE, 
  'Copy Test Case' AS TEST_CASE_FORM_TYPE,
  'Copy Test Case Steps' AS TEST_CASE_STEP_FORM_TYPE,
  :TEST_SET_NAME AS TEST_SET_NAME,
  tc.TEST_CASE_UUID, 
  tc.TEST_CASE_ID, 
  tc.TEST_CASE_NAME, 
  tc.TEST_CASE_NAME AS US_TEST_CASE_NAME, 
  tc.AE_INSERT_ID, 
  tc.AE_UPDATE_ID, 
  tc.AE_INSERT_TS, 
  tc.AE_UPDATE_TS, 
  tc.AE_TRANSACTION_ID, 
  tc.FUNCTIONAL_AREA_UUID, 
  tc.TEST_SET_UUID, 
  tc.TEST_CASE_SEQ_ID, 
  :PROCESS_UUID AS PROCESS_UUID, 
  :PAGE_UUID AS PAGE_UUID, 
  :VIEW_UUID AS VIEW_UUID, 
  :USER_ACTION_UUID AS USER_ACTION_UUID, 
  tc.TEST_CASE_STATUS, 
  tc.TEST_CASE_EXECUTON_TYPE,
  tc.ASSOCIATED_VIEW_UUID, 
  'Test Case' AS GRID_NAME,
  tc.SKIP_STEP_WITH_NO_UI_ELEMENT_VALUE,
  tc.USER_STORY_UUID,
  (
    SELECT COUNT(DISTINCT td.TEST_DATA_SET_UUID)+1
    FROM TEST_DATA_SET td
    WHERE td.PARENT_UUID = tc.TEST_CASE_UUID
  ) AS ColumnData,
  tc.TEST_CASE_OWNER
FROM 
  TEST_CASE tc
WHERE 
  tc.TEST_SET_UUID = :TEST_SET_UUID 
  AND (
    :PARENT_GRID_NAME = 'Unit Functional Test Set' OR 
    :PARENT_GRID_NAME = 'Orphan Test Set' OR 
    :PARENT_GRID_NAME = 'Test Set' OR 
    :PARENT_GRID_NAME = 'Page Navigation Test Set'
  )

UNION

SELECT DISTINCT
  :PARENT_GRID_NAME AS PARENT_GRID_NAME, 
  'LinkedTestCases' AS LINKED_TEST_CASE_GRID, 
  'AllRequirement' AS ALL_REQ_GRID, 
  'TEST_CASE' AS SOURCE_TYPE, 
  'Copy Test Case' AS TEST_CASE_FORM_TYPE,
  'Copy Test Case Steps' AS TEST_CASE_STEP_FORM_TYPE,
  :TEST_SET_NAME AS TEST_SET_NAME,
  tc.TEST_CASE_UUID, 
  tc.TEST_CASE_ID, 
  tc.TEST_CASE_NAME, 
  tc.TEST_CASE_NAME AS US_TEST_CASE_NAME,
  tc.AE_INSERT_ID, 
  tc.AE_UPDATE_ID, 
  tc.AE_INSERT_TS, 
  tc.AE_UPDATE_TS, 
  tc.AE_TRANSACTION_ID, 
  tc.FUNCTIONAL_AREA_UUID, 
  tc.TEST_SET_UUID, 
  tc.TEST_CASE_SEQ_ID, 
  :PROCESS_UUID AS PROCESS_UUID, 
  :PAGE_UUID AS PAGE_UUID, 
  :VIEW_UUID AS VIEW_UUID, 
  :USER_ACTION_UUID AS USER_ACTION_UUID, 
  tc.TEST_CASE_STATUS, 
  tc.TEST_CASE_EXECUTON_TYPE, 
  tc.ASSOCIATED_VIEW_UUID,
  'Test Case' AS GRID_NAME,
  tc.SKIP_STEP_WITH_NO_UI_ELEMENT_VALUE,
  tc.USER_STORY_UUID,
  (
    SELECT COUNT(DISTINCT td.TEST_DATA_SET_UUID)+1
    FROM TEST_DATA_SET td
    WHERE td.PARENT_UUID = tc.TEST_CASE_UUID
  ) AS ColumnData,
  tc.TEST_CASE_OWNER
FROM 
  TEST_CASE tc
WHERE 
  tc.TEST_SET_UUID = :TEST_SET_UUID 
  AND tc.TEST_CASE_OWNER IS NOT NULL 
  AND (
    :PARENT_GRID_NAME = 'Personal Test Set' OR 
    :PARENT_GRID_NAME = 'Personal - Regular Test Set' OR 
    :PARENT_GRID_NAME = 'Personal - Unit Functional Test Set' OR 
    :PARENT_GRID_NAME = 'Personal - Orphan Test Set'
  )
  AND tc.TEST_CASE_OWNER = :APP_LOGGED_IN_USER_ID

ORDER BY TEST_CASE_ID DESC; 